homeassistant:
  name: Home
  latitude: !secret latitude_loc_home
  longitude: !secret longitude_loc_home
  elevation: 387
  unit_system: imperial
  time_zone: America/Phoenix
  packages: !include_dir_named packages

config:
conversation:
#discovery:
frontend:
  themes:
    dark:
      primary-color: "#485F6B"
sun:
updater:
history:


