homeassistant:
  name: Home
  latitude: !secret latitude_loc_home
  longitude: !secret longitude_loc_home
  elevation: 387
  unit_system: imperial
  time_zone: America/Phoenix
  packages: !include_dir_named packages

automation: !include_dir_merge_list automation/

config:
conversation:
#discovery:
frontend:
sun:
updater:
history:
#  exclude:
#    domains:
#      - camera
#      - input_select
#      - input_slider
#      - media_player
#      - zwave

#    entities:
#      - sensor.date__time
#      - sensor.megs_eta
#      - sensor.ricks_eta
#      - sensor.megs_eta_home
#      - sensor.rick_eta_home
#      - sensor.dark_sky_cloud_coverage
#      - sensor.dark_sky_daily_summary
#      - sensor.dark_sky_nearest_storm_distance
#      - sensor.pws_temp_f
#      - sensor.pws_feelslike_string
#      - sensor.pws_precip_today_string
#      - sensor.pws_wind_string
#      - sensor.pws_wind_dir
#      - sensor.pws_heat_index_string
#      - sensor.pws_relative_humidity
#      - sensor.pws_dewpoint_string
#      - sensor.pws_pressure_in
#      - sensor.pws_pressure_mb
#      - sensor.pws_solarradiation
#      - sensor.pws_uv
#      - sensor.pws_observation_time
#      - sensor.pws_visibility_mi
#      - automation.random_flux_rgb
#      - automation.rgb_blue
#      - automation.rgb_cool
#      - automation.rgb_cyan
#      - automation.rgb_green
#      - automation.rgb_off
#      - automation.rgb_pink
#      - automation.rgb_red
#      - automation.rgb_violet
#      - automation.rgb_yellow
