- platform: amcrest
  host: !secret north_ptz_host
  port: !secret north_ptz_port
  name: "North PTZ"
  username: !secret camera_user
  password: !secret camera_password
  monitored_conditions:
    - motion_detector
#    - sdcard
#    - ptz_preset

- platform: amcrest
  host: !secret kitchen_ptz_host
  port: !secret kitchen_ptz_port
  name: "Kitchen PTZ"
  username: !secret camera_user
  password: !secret camera_password
  monitored_conditions:
    - motion_detector
#    - sdcard
#    - ptz_preset