
#####################################################################
### BATTERY STATUS- DEVICES
#####################################################################

## sensor: iCloud Battery - Rick
- platform: template
  sensors:
    iphone_battery_rick:
      friendly_name: "Rick's Phone Battery"
      value_template: >-
        {%- if states.device_tracker.iphwn666.attributes.battery | round(2) != None -%}
          {{ states.device_tracker.iphwn666.attributes.battery | round(2) }}
        {%- else -%}
          Unknown
        {%- endif -%}
      unit_of_measurement: '%'

## sensor: iCloud Battery - Megs
- platform: template
  sensors:
    iphone_battery_megs:
      friendly_name: "Meg's Phone Battery"
      value_template: >-
        {%- if states.device_tracker.iphone7.attributes.battery | round(2) != None -%}
          {{ states.device_tracker.iphone7.attributes.battery | round(2) }}
        {%- else -%}
          Unknown
        {%- endif -%}
      unit_of_measurement: '%'

#####################################################################
### BATTERY STATUS - LOCKS
#####################################################################

## Beach Bathroom Lock Battery
- platform: template
  sensors:
    lock_beach_battery:
      friendly_name: "Beach Lock Battery"
      value_template: >-
        {%- if states.lock.assa_abloy_yale_real_living_captouch_lever_locked_12_0.attributes.battery_level != None -%}
          {{ states.lock.assa_abloy_yale_real_living_captouch_lever_locked_12_0.attributes.battery_level }}
        {%- else -%}
          Unknown
        {%- endif -%}
      unit_of_measurement: '%'

## South Lock Battery
- platform: template
  sensors:
    lock_south_battery:
      friendly_name: "South Lock Battery"
      value_template: >-
        {%- if states.lock.assa_abloy_yale_real_living_captouch_lever_locked_16_0.attributes.battery_level != None -%}
          {{ states.lock.assa_abloy_yale_real_living_captouch_lever_locked_16_0.attributes.battery_level }}
        {%- else -%}
          Unknown
        {%- endif -%}
      unit_of_measurement: '%'
