#####################################################################
### Seasons
#####################################################################

- platform: template
  sensors:
    season:
      friendly_name: "Seasonal Condition"
      value_template: >-
        {% set temperature = states('sensor.pws_temp_f')|float(none) %}
        {% set winter_temp = states.input_slider.season_winter.state|default(62)|float %}
        {% set summer_temp = states.input_slider.season_summer.state|default(74)|float %}
        {% if temperature is none %}
          {{ states('sensor.pws_temp_f') }}
        {% elif temperature < winter_temp %}
          Winter
        {% elif temperature > summer_temp %}
          Summer
        {% else %}
          Awesome
        {% endif %}

#####################################################################
### Downstairs Climate Control
#####################################################################

- platform: template
  sensors:
    ds_climate_control:
      friendly_name: "Downstairs Climate Control"
      value_template: >-
        {% set temperature = states('sensor.2gig_technologies_ct101_thermostat_iris_temperature_18_1')|float(none) %}
        {% set ds_low = states.input_slider.ds_low.state|default(69)|float %}
        {% set ds_high = states.input_slider.ds_high.state|default(79)|float %}
        {% if temperature is none %}
          {{ states('sensor.2gig_technologies_ct101_thermostat_iris_temperature_18_1') }}
        {% elif temperature < ds_low %}
          Cold
        {% elif temperature > ds_high %}
          Hot
        {% else %}
          Comfy
        {% endif %}

#####################################################################
### Upstairs Climate Control
#####################################################################

- platform: template
  sensors:
    us_climate_control:
      friendly_name: "Upstairs Climate Control"
      value_template: >-
        {% set temperature = states('sensor.2gig_technologies_ct101_thermostat_iris_temperature_42_1')|float(none) %}
        {% set us_low = states.input_slider.us_low.state|default(68)|float %}
        {% set us_high = states.input_slider.us_high.state|default(81)|float %}
        {% if temperature is none %}
          {{ states('sensor.2gig_technologies_ct101_thermostat_iris_temperature_42_1') }}
        {% elif temperature < us_low %}
          Cold
        {% elif temperature > us_high %}
          Hot
        {% else %}
          Comfy
        {% endif %}
