#####################################################################
### HVAC Downstairs
#####################################################################
## Median Temperature Downstairs
- platform: statistics
  entity_id: sensor.2gig_technologies_ct101_thermostat_iris_temperature_18_1
  name: Downstairs Thermostat Statistics

- platform: template
  sensors:
## Downstairs Thermostat Mode
    hvac_downstairs_mode:
      friendly_name: "Downstairs Thermostat Mode"
## This automatically returns "unknown" if the state is not set
      value_template: "{{ states('climate.2gig_technologies_ct101_thermostat_iris_cooling_1_18_2') }}"

## Downstairs Operating State
    hvac_downstairs_op_state:
      friendly_name: "Downstairs HVAC State"
      value_template: "{{ (states.climate['2gig_technologies_ct101_thermostat_iris_cooling_1_18_2'].attributes|default({})).operating_state|default('unknown') }}"

## Downstairs Fan State
    hvac_downstairs_fan:
      friendly_name: "Downstairs HVAC Fan"
      value_template: "{{ (states.climate['2gig_technologies_ct101_thermostat_iris_cooling_1_18_2'].attributes|default({})).fan_state|default('unknown') }}"

## Downstairs AC Temp Setpoint
    hvac_downstairs_ac_setpoint:
      friendly_name: "Downstairs AC Setpoint"
      value_template: "{{ (states.climate['2gig_technologies_ct101_thermostat_iris_cooling_1_18_2'].attributes|default({})).temperature|default('unknown') }}"

## Downstairs Heat Temp Setpoint
    hvac_downstairs_heat_setpoint:
      friendly_name: "Downstairs Heat Setpoint"
      value_template: "{{ (states.climate['2gig_technologies_ct101_thermostat_iris_heating_1_18_1'].attributes|default({})).temperature|default('unknown') }}"
