## Seasons
- platform: template
  sensors:
    season:
      friendly_name: "Season"
      # @dale3h: Added optional input_slider to set temperature thresholds
      value_template: >-
        {% set temperature = states('sensor.pws_temp_f')|float(none) %}
        {% set winter_temp = states.input_slider.season_winter.state|default(69)|float %}
        {% set summer_temp = states.input_slider.season_summer.state|default(80)|float %}

        {% if temperature is none %}
          {{ states('sensor.pws_temp_f') }}
        {% elif temperature < winter_temp %}
          Winter
        {% elif temperature > summer_temp %}
          Summer
        {% else %}
          Awesome
        {% endif %}


### Seasons
#- platform: template
#  sensors:
#    season:
#      friendly_name: "Season"
#      value_template: >-
#        {%- if states('sensor.pws_temp_f') == None -%}
#            Unknown
#        {%- elif 70 <= states('sensor.pws_temp_f') | float <= 83 -%}
#            Awesome
#        {%- elif states('sensor.pws_temp_f') | float < 70 -%}
#          Winter
#        {%- elif states('sensor.pws_temp_f') | float > 83 -%}
#          Summer
#        {%- else -%}
#            states('sensor.pws_temp_f')
#        {%- endif %}

