#####################################################################
### Set Temperature Thresholds on peak hours or away
#####################################################################
- alias: set temperature thresholds on peak or away
  trigger:
    - platform: state
      entity_id: group.family
      from: 'on'
      to: 'off'
      for:
        minutes: 15

    - platform: state
      entity_id: input_boolean.peak_hours
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: input_boolean.visitor_mode
      state: 'off'

  action:
## Set Summer and Winter thresholds
    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.season_summer
        value: 86

    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.season_winter
        value: 50

## Set Temperature thresholds
    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.ds_high
        value: 83

    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.us_high
        value: 87

    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.ds_low
        value: 66

    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.us_low
        value: 66

#####################################################################
### Set Temperature Thresholds upon return
#####################################################################
- alias: set temperature thresholds on arrival
  trigger:
    platform: state
    entity_id: group.family
    from: 'off'
    to: 'on'
    for:
      minutes: 2

  action:
## Set Summer and Winter thresholds
    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.season_summer
        value: 83

    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.season_winter
        value: 50

## Set Temperature thresholds
    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.ds_high
        value: 79

    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.us_high
        value: 83

    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.ds_low
        value: 69

    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.us_low
        value: 68