#####################################################################
### AC - Upstairs Upper Limit Reached
#####################################################################
- alias: cool upstairs if too hot
  trigger:
    - platform: numeric_state
      entity_id: sensor.2gig_technologies_ct101_thermostat_iris_temperature_24_1
      above: 87

  action:
    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.upstairs_ac
        value: 77

    - delay: 00:60:00

    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.upstairs_ac
        value: 85

#####################################################################
### AC - Upstairs Comfort Zone Reached
#####################################################################
- alias: upstairs comfort zone reached
  trigger:
    - platform: numeric_state
      entity_id: sensor.2gig_technologies_ct101_thermostat_iris_temperature_24_1
      below: 81

  condition:
    - condition: state
      entity_id: climate.2gig_technologies_ct101_thermostat_iris_cooling_1_24_2
      state: 'Cool'

  action:
    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.upstairs_ac
        value: 83

#####################################################################
### AC - Upstairs Cooling Trigger
#####################################################################
- alias: upstairs cooling triggered
  trigger:
    - platform: state
      entity_id: sensor.us_climate_control
      to: 'Hot'

    - platform: state
      entity_id: input_boolean.peak_hours
      to: 'off'

  condition:
    - condition: state
      entity_id: climate.2gig_technologies_ct101_thermostat_iris_cooling_1_24_2
      state: 'Cool'

    - condition: or
      conditions:
        - condition: state
          entity_id: group.family
          state: 'on'

        - condition: state
          entity_id: input_boolean.visitor_mode
          state: 'on'

  action:
    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.upstairs_ac
        value: 82

#####################################################################
### AC - Upstairs Weekday Mornings
#####################################################################
- alias: upstairs cooling weekday mornings
  trigger:
    - platform: time
      after: '03:44:59'

  condition:
    - condition: state
      entity_id: climate.2gig_technologies_ct101_thermostat_iris_cooling_1_24_2
      state: 'Cool'

    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri

    - condition: or
      conditions:
        - condition: state
          entity_id: group.family
          state: 'on'

        - condition: state
          entity_id: input_boolean.visitor_mode
          state: 'on'

  action:
    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.upstairs_ac
        value: 82

#####################################################################
### AC - Upstairs Weekday Nights
#####################################################################
- alias: upstairs cooling weekday nights
  trigger:
    - platform: time
      after: '20:29:59'

  condition:
    - condition: state
      entity_id: climate.2gig_technologies_ct101_thermostat_iris_cooling_1_24_2
      state: 'Cool'

    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - sun

    - condition: or
      conditions:
        - condition: state
          entity_id: group.family
          state: 'on'

        - condition: state
          entity_id: input_boolean.visitor_mode
          state: 'on'

  action:
    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.upstairs_ac
        value: 77

    - delay: 02:00:00

    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.upstairs_ac
        value: 82

#####################################################################
### AC - Upstairs Weekends
#####################################################################
- alias: upstairs cooling weekend nights
  trigger:
    - platform: time
      after: '22:29:59'

  condition:
    - condition: state
      entity_id: climate.2gig_technologies_ct101_thermostat_iris_cooling_1_24_2
      state: 'Cool'

    - condition: time
      weekday:
        - fri
        - sat

    - condition: or
      conditions:
        - condition: state
          entity_id: group.family
          state: 'on'

        - condition: state
          entity_id: input_boolean.visitor_mode
          state: 'on'

  action:
    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.upstairs_ac
        value: 77

    - delay: 02:00:00

    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.upstairs_ac
        value: 82
