#####################################################################
### HEAT - Downstairs Heating Schedule
#####################################################################
- alias: downstairs heating schedule
  trigger:
    - platform: time
      after: '05:59:59'

  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: group.family
          state: 'on'

        - condition: state
          entity_id: input_boolean.visitor_mode
          state: 'on'

  action:
    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.downstairs_heat
        value: 71

#####################################################################
### HEAT - Downstairs - Off Peak
#####################################################################
- alias: downstairs heating off peak
  trigger:
    - platform: state
      entity_id: input_boolean.peak_hours
      from: 'on'
      to: 'off'

  condition:
    - condition: numeric_state
      entity_id: sensor.2gig_technologies_ct101_thermostat_iris_temperature_18_1
      below: 70

    - condition: or
      conditions:
        - condition: state
          entity_id: group.family
          state: 'on'

        - condition: state
          entity_id: input_boolean.visitor_mode
          state: 'on'

  action:
    - service: script.heat_downstairs_60min

#####################################################################
### HEAT - Lower temp at bedtime or after hours
#####################################################################
- alias: heat downstairs bedtime
  trigger:
    - platform: state
      entity_id: script.bedtime
      from: 'off'
      to: 'on'

    - platform: state
      entity_id: input_boolean.after_hours
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: climate.2gig_technologies_ct101_thermostat_iris_cooling_1_18_2
      state: 'Heat'

  action:
    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.downstairs_heat
        value: 66
