#####################################################################
### AC - Upstairs Cooling Schedule 1
#####################################################################
- alias: upstairs cooling schedule 1
  trigger:
    - platform: time
      at: '02:00:00'

  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: group.all_devices
          state: 'home'

        - condition: state
          entity_id: input_boolean.visitor_mode
          state: 'on'

  action:
    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.upstairs_ac
        value: 82

#####################################################################
### AC - Upstairs Cooling Schedule 2
#####################################################################
- alias: upstairs cooling schedule 2
  trigger:
    - platform: time
      at: '12:00:00'

  action:
    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.upstairs_ac
        value: 90

#####################################################################
### AC - Upstairs Cooling Schedule 3
#####################################################################
- alias: upstairs cooling schedule 3
  trigger:
    - platform: time
      at: '18:00:00'

  action:
    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.upstairs_ac
        value: 84

#####################################################################
### AC - Upstairs Cooling Schedule 4
#####################################################################
- alias: upstairs cooling schedule 4
  trigger:
    - platform: state
      entity_id: script.bedtime
      to: 'on'

    - platform: state
      entity_id: script.master_bedroom_night_time
      to: 'on'

    - platform: time
      at: '19:00:00'

  condition:
    - condition: numeric_state
      entity_id: sensor.upstairs_thermostat_temperature
      above: 82

    - condition: numeric_state
      entity_id: sensor.pws_temp_f
      above: 75

    - condition: or
      conditions:
        - condition: state
          entity_id: group.all_devices
          state: 'home'

        - condition: state
          entity_id: input_boolean.visitor_mode
          state: 'on'

  action:
    - service: script.cool_upstairs_60min
