#####################################################################
### HVAC UPSTAIRS; SET AWESOME
#####################################################################
- alias: hvac upstairs awesome
  trigger:
    - platform: state
      entity_id: sensor.season
      to: 'Awesome'

  condition:
    - condition: numeric_state
      entity_id: sensor.upstairs_thermostat_temperature
      below: 81

    - condition: numeric_state
      entity_id: sensor.upstairs_thermostat_temperature
      above: 66

  action:
    - service: script.turn_off
      entity_id:
        - script.cool_upstairs_60min
        - script.heat_upstairs_60min

    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.upstairs_ac
        value: 81

    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.upstairs_heat
        value: 67

    - service: group.set_visibility
      entity_id: group.upstairs_cooling
      data:
        visible: True

    - service: group.set_visibility
      entity_id: group.upstairs_heating
      data:
        visible: True

#####################################################################
### HVAC UPSTAIRS; SET COOL
#####################################################################
- alias: hvac upstairs mode cool
  hide_entity: True
  trigger:
    - platform: state
      entity_id: sensor.season
      to: 'Summer'

    - platform: template
      value_template: "{% if is_state('sensor.season', 'Summer') %}true{% endif %}"

  action:
    - service: group.set_visibility
      entity_id: group.upstairs_cooling
      data:
        visible: True

    - service: group.set_visibility
      entity_id: group.upstairs_heating
      data:
        visible: False

    - service: climate.set_operation_mode
      entity_id: climate.upstairs_thermostat_cooling_1
      data:
        operation_mode: 'Cool'

#####################################################################
### HVAC UPSTAIRS; SET HEAT
#####################################################################
- alias: hvac upstairs mode heat
  hide_entity: True
  trigger:
    - platform: state
      entity_id: sensor.season
      to: 'Winter'

    - platform: template
      value_template: "{% if is_state('sensor.season', 'Winter') %}true{% endif %}"

  action:
    - service: group.set_visibility
      entity_id: group.upstairs_heating
      data:
        visible: True

    - service: group.set_visibility
      entity_id: group.upstairs_cooling
      data:
        visible: False

    - service: climate.set_operation_mode
      entity_id: climate.upstairs_thermostat_cooling_1
      data:
        operation_mode: 'Heat'
