#####################################################################
### AC - Upstairs Cooling Schedule
#####################################################################
- alias: upstairs cooling schedule
  trigger:
    - platform: time
      after: '03:59:59'

  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: group.family
          state: 'on'

        - condition: state
          entity_id: input_boolean.visitor_mode
          state: 'on'

  action:
    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.upstairs_ac
        value: 82

#####################################################################
### AC - Upstairs Cooling - Off Peak
#####################################################################
- alias: upstairs cooling off peak
  trigger:
    - platform: state
      entity_id: input_boolean.peak_hours
      from: 'on'
      to: 'off'

  condition:
    - condition: numeric_state
      entity_id: sensor.2gig_technologies_ct101_thermostat_iris_temperature_24_1
      above: 80

    - condition: or
      conditions:
        - condition: state
          entity_id: group.family
          state: 'on'

        - condition: state
          entity_id: input_boolean.visitor_mode
          state: 'on'

  action:
    - service: script.cool_upstairs_60min

#####################################################################
### AC - Upstairs Bedtime
#####################################################################
- alias: upstairs cooling bedtime
  trigger:
    - platform: state
      entity_id: script.bedtime
      to: 'on'

  condition:
    - condition: numeric_state
      entity_id: sensor.2gig_technologies_ct101_thermostat_iris_temperature_24_1
      above: 82

    - condition: numeric_state
      entity_id: sensor.pws_temp_f
      above: 75

    - condition: state
      entity_id: script.cool_upstairs_120min
      state: 'off'

    - condition: state
      entity_id: script.cool_upstairs_180min
      state: 'off'

  action:
    - service: script.cool_upstairs_60min
