#####################################################################
### HEAT - Upstairs Heating Schedule
#####################################################################
- alias: upstairs heating schedule
  trigger:
    - platform: time
      at: '04:00:00'

  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: group.all_devices
          state: 'home'

        - condition: state
          entity_id: input_boolean.visitor_mode
          state: 'on'

  action:
    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.upstairs_heat
        value: 69

#####################################################################
### HEAT - Upstairs - Off Peak
#####################################################################
- alias: upstairs heating off peak
  trigger:
    - platform: state
      entity_id: input_boolean.peak_hours
      from: 'on'
      to: 'off'

  condition:
    - condition: numeric_state
      entity_id: sensor.2gig_technologies_ct101_thermostat_iris_temperature_42_1
      below: 68

    - condition: or
      conditions:
        - condition: state
          entity_id: group.all_devices
          state: 'home'

        - condition: state
          entity_id: input_boolean.visitor_mode
          state: 'on'

  action:
    - service: script.heat_upstairs_60min

#####################################################################
### HEAT - Upstairs Bedtime
#####################################################################
- alias: upstairs heating bedtime
  trigger:
    - platform: state
      entity_id: script.bedtime
      to: 'on'

  condition:
    - condition: numeric_state
      entity_id: sensor.2gig_technologies_ct101_thermostat_iris_temperature_42_1
      below: 69

    - condition: numeric_state
      entity_id: sensor.pws_temp_f
      below: 57

  action:
    - service: script.heat_upstairs_60min
