#####################################################################
### HVAC DOWNSTAIRS; SET AWESOME
#####################################################################
- alias: hvac downstairs awesome
  trigger:
    - platform: state
      entity_id: sensor.season
      to: 'Awesome'

  condition:
    - condition: numeric_state
      entity_id: sensor.2gig_technologies_ct101_thermostat_iris_temperature_18_1
      below: 79

    - condition: numeric_state
      entity_id: sensor.2gig_technologies_ct101_thermostat_iris_temperature_18_1
      above: 66

  action:
    - service: script.turn_off
      entity_id:
        - script.cool_stairs_60min
        - script.cool_stairs_120min
        - script.cool_stairs_180min
        - script.heat_stairs_60min
        - script.heat_stairs_120min
        - script.heat_downstairs_180min

    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.downstairs_ac
        value: 81

    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.downstairs_heat
        value: 66

    - service: group.set_visibility
      entity_id: group.downstairs_cooling
      data:
        visible: True

    - service: group.set_visibility
      entity_id: group.downstairs_heating
      data:
        visible: True

#####################################################################
### HVAC DOWNSTAIRS; SET COOL
#####################################################################
- alias: hvac downstairs mode cool
  hide_entity: True
  trigger:
    - platform: state
      entity_id: sensor.season
      to: 'Summer'

    - platform: template
      value_template: "{% if is_state('sensor.season', 'Summer') %}true{% endif %}"

  action:
    - service: group.set_visibility
      entity_id: group.downstairs_cooling
      data:
        visible: True

    - service: group.set_visibility
      entity_id: group.downstairs_heating
      data:
        visible: False

    - service: climate.set_operation_mode
      entity_id: climate.2gig_technologies_ct101_thermostat_iris_cooling_1_18_2
      data:
        operation_mode: 'Cool'

#####################################################################
### HVAC DOWNSTAIRS; SET HEAT
#####################################################################
- alias: hvac downstairs mode heat
  hide_entity: True
  trigger:
    - platform: state
      entity_id: sensor.season
      to: 'Winter'

    - platform: template
      value_template: "{% if is_state('sensor.season', 'Winter') %}true{% endif %}"

  action:
    - service: group.set_visibility
      entity_id: group.downstairs_heating
      data:
        visible: True

    - service: group.set_visibility
      entity_id: group.downstairs_cooling
      data:
        visible: False

    - service: climate.set_operation_mode
      entity_id: climate.2gig_technologies_ct101_thermostat_iris_cooling_1_18_2
      data:
        operation_mode: 'Heat'
