#####################################################################
### HVAC UPSTAIRS; SET OFF; Turn off the system if the weather is awesome!
#####################################################################
- alias: hvac upstairs off if awesome weather
  trigger:
    - platform: state
      entity_id: sensor.season
      to: 'Awesome'

    - platform: template
      value_template: "{% if is_state('sensor.season', 'Awesome') %}true{% endif %}"

  condition:
    - condition: state
      entity_id: sensor.us_climate_control
      state: 'Comfy'

  action:
    - service: climate.set_operation_mode
      entity_id: climate.2gig_technologies_ct101_thermostat_iris_cooling_1_24_2
      data:
        operation_mode: 'Off'

#####################################################################
### HVAC UPSTAIRS; SET COOL
#####################################################################
- alias: hvac upstairs mode cool
  hide_entity: True
  trigger:
    - platform: state
      entity_id: sensor.season
      to: 'Summer'

    - platform: template
      value_template: "{% if is_state('sensor.season', 'Summer') %}true{% endif %}"

    - platform: state
      entity_id: sensor.us_climate_control
      to: 'Hot'

  action:
    - service: group.set_visibility
      entity_id: group.upstairs_cooling
      data:
        visible: True

    - service: group.set_visibility
      entity_id: group.upstairs_heating
      data:
        visible: False

    - service: climate.set_operation_mode
      entity_id: climate.2gig_technologies_ct101_thermostat_iris_cooling_1_24_2
      data:
        operation_mode: 'Cool'

#####################################################################
### HVAC UPSTAIRS; SET HEAT
#####################################################################
- alias: hvac upstairs mode heat
  hide_entity: True
  trigger:
    - platform: state
      entity_id: sensor.season
      to: 'Winter'

    - platform: template
      value_template: "{% if is_state('sensor.season', 'Winter') %}true{% endif %}"

    - platform: state
      entity_id: sensor.us_climate_control
      to: 'Cold'

  action:
    - service: group.set_visibility
      entity_id: group.upstairs_heating
      data:
        visible: True

    - service: group.set_visibility
      entity_id: group.upstairs_cooling
      data:
        visible: False

    - service: climate.set_operation_mode
      entity_id: climate.2gig_technologies_ct101_thermostat_iris_cooling_1_24_2
      data:
        operation_mode: 'Heat'
