#####################################################################
### AC - Downstairs Cooling Schedule
#####################################################################
- alias: downstairs cooling schedule
  trigger:
    - platform: time
      at: '06:00:00'

    - platform: time
      at: '19:30:00'

  condition:
    - condition: state
      entity_id: script.cool_downstairs_60min
      state: 'off'

    - condition: or
      conditions:
        - condition: state
          entity_id: group.all_devices
          state: 'home'

        - condition: state
          entity_id: input_boolean.visitor_mode
          state: 'on'

  action:
    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.downstairs_ac
        value: 78

#####################################################################
### AC - Downstairs Pre-Cooling
#####################################################################
- alias: downstairs pre-cooling
  trigger:
    - platform: time
      at: '13:00:00'

  condition:
    - condition: state
      entity_id: script.cool_downstairs_60min
      state: 'off'

    - condition: or
      conditions:
        - condition: state
          entity_id: group.all_devices
          state: 'home'

        - condition: state
          entity_id: input_boolean.visitor_mode
          state: 'on'

  action:
    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.downstairs_ac
        value: 75

#####################################################################
### AC - Downstairs Cooling - Off Peak
#####################################################################
- alias: downstairs cooling off peak
  trigger:
    - platform: state
      entity_id: input_boolean.peak_hours
      from: 'on'
      to: 'off'

  condition:
    - condition: numeric_state
      entity_id: sensor.2gig_technologies_ct101_thermostat_iris_temperature_18_1
      above: 78

    - condition: numeric_state
      entity_id: sensor.pws_temp_f
      above: 76

    - condition: or
      conditions:
        - condition: state
          entity_id: group.all_devices
          state: 'home'

        - condition: state
          entity_id: input_boolean.visitor_mode
          state: 'on'

  action:
    - service: script.cool_downstairs_60min

#####################################################################
### AC - Raise temp at bedtime or after hours
#####################################################################
- alias: cool downstairs bedtime
  trigger:
    - platform: state
      entity_id: script.bedtime
      from: 'off'
      to: 'on'

    - platform: state
      entity_id: input_boolean.after_hours
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: climate.2gig_technologies_ct101_thermostat_iris_cooling_1_18_2
      state: 'Cool'

  action:
    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.downstairs_ac
        value: 81
