#####################################################################
### Set Temperature Thresholds on away
#####################################################################
- alias: set temperature thresholds on away
  trigger:
    - platform: state
      entity_id: group.family
      from: 'on'
      to: 'off'
      for:
        minutes: 15

  condition:
    - condition: state
      entity_id: input_boolean.visitor_mode
      state: 'off'

  action:
########################
### Set Downstairs Values
########################
    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.downstairs_ac
        value: 82

    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.downstairs_heat
        value: 66

########################
### Set Upstairs Values
########################
    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.upstairs_ac
        value: 87

    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.upstairs_heat
        value: 66

#####################################################################
### Set Temperature Thresholds upon return
#####################################################################
- alias: set temperature thresholds on arrival
  trigger:
    platform: state
    entity_id: group.family
    from: 'off'
    to: 'on'
    for:
      minutes: 2

  action:
########################
### Set Downstairs Values
########################
    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.downstairs_ac
        value: 78

    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.downstairs_heat
        value: 69

########################
### Set Upstairs Values
########################
    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.upstairs_ac
        value: 82

    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.upstairs_heat
        value: 68

#####################################################################
### Set Temperature Thresholds on peak hours
#####################################################################
- alias: set temperature thresholds on peak hours
  trigger:
    - platform: state
      entity_id: input_boolean.peak_hours
      from: 'off'
      to: 'on'

  action:
########################
### Set Downstairs Values
########################
    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.downstairs_ac
        value: 81

    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.downstairs_heat
        value: 67

########################
### Set Upstairs Values
########################
    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.upstairs_ac
        value: 86

    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.upstairs_heat
        value: 67