#####################################################################
### Peak Hours ON
#####################################################################

- alias: peak hours on
  hide_entity: True
  trigger:
    - platform: time
      after: '14:59:59'

  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.peak_hours

#####################################################################
### Peak Hours OFF
#####################################################################

- alias: peak hours off
  hide_entity: True
  trigger:
    - platform: time
      after: '17:59:59'

  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.peak_hours

#####################################################################
### After Hours ON Weekdays
#####################################################################

- alias: after hours on weekdays
  hide_entity: True
  trigger:
    - platform: time
      after: '23:29:59'

  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - sun

  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.after_hours

#####################################################################
### After Hours OFF Weekdays
#####################################################################

- alias: after hours off weekdays
  hide_entity: True
  trigger:
    - platform: time
      after: '03:59:59'

  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri

  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.after_hours

#####################################################################
### After Hours ON Weekends
#####################################################################

- alias: after hours on weekends
  hide_entity: True

  trigger:
    - platform: time
      after: '01:59:59'

  condition:
    - condition: time
      weekday:
        - sat
        - sun

  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.after_hours

#####################################################################
### After Hours OFF Weekends
#####################################################################

- alias: after hours off weekends
  hide_entity: True
  trigger:
    - platform: time
      after: '07:59:59'

  condition:
    - condition: time
      weekday:
        - sat
        - sun

  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.after_hours

#####################################################################
### RAIN SENSOR ON/OFF
#####################################################################

- alias: rain sensor
  hide_entity: True
  trigger:
    - platform: state
      entity_id: sensor.pws_weather

#  condition:
#    - condition: or
#      conditions:
#        - condition: template
#          value_template: "{{ is_state('sensor.pws_weather', 'Rain') }}"
#        - condition: template
#          value_template: "{{ is_state('sensor.pws_weather', 'Thunderstorm') }}"

  action:
    - service_template: >-
        {% if is_state('sensor.pws_weather', 'Rain') %}
          homeassistant.turn_on
        {% elif is_state('sensor.pws_weather', 'Thunderstorm') %}
          homeassistant.turn_on
        {% else %}
          homeassistant.turn_off
        {% endif %}
      data:
        entity_id: input_boolean.rain