####################################################################
### Adjust lighting scenes based on Kodi playback state
####################################################################
- alias: Kodi Scene Set
  hide_entity: True
  trigger:
    - platform: state
      entity_id: media_player.kodi_living_room

  condition: 
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'

  action:
    - service: scene.turn_on
      data_template:
        entity_id: >-
          {% if trigger.to_state.state == "playing" or trigger.to_state.state == "resumed" %}
            scene.movie_time
          {% elif trigger.to_state.state == "paused" or trigger.to_state.state == "idle" %}
            scene.movie_paused
          {% elif trigger.to_state.state == "stopped" or trigger.to_state.state == "ended" %}
            scene.movie_ended
          {% else %}
            scene.living_room_dim
          {% endif %}
