#####################################################################
### Turn on the porch lights at sunset
#####################################################################

- alias: porch lights on at sunset
  hide_entity: True
  trigger:
    - platform: sun
      event: sunset
      offset: '00:10:00'

  action:
    - service: homeassistant.turn_on
      entity_id: group.porch

#####################################################################
### Turn off the porch lights
#####################################################################

- alias: porch lights off at sunrise
  hide_entity: True
  trigger:
    - platform: sun
      event: sunrise
      offset: '-00:15:00'

  action:
    - service: homeassistant.turn_off
      entity_id: group.porch
