#####################################################################
#    @package          :     security_cameras
#    @description      :     security_cameras and associated automations, etc.
#####################################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'cameras'

      contained: &contained
        <<: *customize
        haaska_hidden: true
        homebridge_hidden: true

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

      hidden: &hidden
        <<: *contained
        hidden: true

    ################################################
    ## Group
    ################################################
    group.cameras:
      <<: *contained
      order: 1

    group.traffic_report:
      <<: *contained


#####################################################################
### Group
#####################################################################
group:
  Cameras:
    entities:
      - camera.front_door
      - camera.gate
      - camera.north_ptz
      - camera.kitchen_ptz
      - sensor.kitchen_ptz_ptz_preset
      - sensor.north_ptz_ptz_preset
      - sensor.kitchen_ptz_sd_used
      - sensor.north_ptz_sd_used

  Traffic Report:
    entities:
      - camera.east_valley_traffic
      - camera.inbound_traffic
      - camera.downtown_traffic
      - camera.ramp_traffic

#####################################################################
### Camera
#####################################################################
camera:
  - platform: generic
    still_image_url: !secret front_door_url
    name: Front Door
    username: !secret camera_user
    password: !secret camera_password

  - platform: generic
    still_image_url: !secret north_gate_url
    name: Gate
    username: !secret camera_user
    password: !secret camera_password

  - platform: generic
    still_image_url: !secret ev_image_url
    name: East Valley Traffic

  - platform: generic
    still_image_url: !secret ib_image_url
    name: Inbound Traffic

  - platform: generic
    still_image_url: !secret dt_image_url
    name: Downtown Traffic

  - platform: generic
    still_image_url: !secret 10_ramp_url
    name: Ramp Traffic

  - platform: generic
    still_image_url: !secret doppler_url
    name: Weather

#####################################################################
### Amcrest
#####################################################################
amcrest:
  ### NORTH PTZ
  - host: !secret north_ptz_host
    name: North PTZ
    username: !secret camera_user
    password: !secret camera_password
    port: !secret north_ptz_port
    resolution: low
    stream_source: rtsp
    sensors:
      - motion_detector

  ### KITCHEN PTZ
  - host: !secret kitchen_ptz_host
    name: Kitchen PTZ
    username: !secret camera_user
    password: !secret camera_password
    port: !secret kitchen_ptz_port
    resolution: low
    stream_source: rtsp
    sensors:
      - motion_detector


### Generic configuration for Amcrest Cameras - retire once Amcrest component is working properly
### NORTH PTZ
#  - platform: generic
#    still_image_url: !secret north_ptz_url
#    name: North PTZ
#    username: !secret camera_user
#    password: !secret camera_password
#    authentication: digest
#
### KITCHEN PTZ
#  - platform: generic
#    still_image_url: !secret kitchen_ptz_url
#    name: Kitchen PTZ
#    username: !secret camera_user
#    password: !secret camera_password
#    authentication: digest


