############################################################################
#    @package          :     climate_upstairs
#    @description      :     climate_upstairs, and associated automations, scenes, etc.
############################################################################
homeassistant:
  customize_glob:
    "sensor.hvac*mode":
      icon: mdi:nest-thermostat

  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'climate_upstairs'

      contained: &contained
        <<: *customize
        haaska_hidden: true
        homebridge_hidden: true

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

      hidden: &hidden
        <<: *contained
        hidden: true

    ################################################
    ## Group
    ################################################
    group.upstairs_climate:
      <<: *contained
      #order: 1

    group.upstairs_cooling:
      <<: *contained
      #order: 2

    group.upstairs_heating:
      <<: *contained
      #order: 3

    script.hvac_operating_mode:
      <<: *contained

    ################################################
    ## Sensor
    ################################################
    sensor.upstairs_thermostat_temperature:
      <<: *contained
      friendly_name: "Upstairs Temp"

    sensor.hvac_upstairs_op_state:
      <<: *contained
      icon: mdi:air-conditioner

    sensor.hvac_upstairs_fan:
      <<: *contained
      icon: mdi:fan

    sensor.hvac_upstairs_ac_setpoint:
      <<: *contained
      icon: mdi:snowflake

    sensor.hvac_upstairs_heat_setpoint:
      <<: *contained
      icon: mdi:fire

    sensor.upstairs_thermostat_statistics_mean:
      <<: *contained
      friendly_name: Upstairs Thermostat Mean Temp
      icon: mdi:chart-areaspline

    sensor.hvac_upstairs_climate:
      <<: *contained
      icon: mdi:air-conditioner

    ################################################
    ## Climate
    ################################################
    climate.upstairs_thermostat_cooling_1:
      <<: *contained
      friendly_name: "Upstairs Cooling Setpoint"

    climate.upstairs_thermostat_heating_1:
      <<: *contained
      friendly_name: "Upstairs Heating Setpoint"

    ################################################
    ## Script
    ################################################
    script.heat_upstairs_60min:
      friendly_name: "Upstairs Quick Heating"
      entity_picture: /local/flame.png

    script.cool_upstairs_60min:
      friendly_name: "Upstairs Quick Cooling"
      entity_picture: /local/snowflake.png

    ################################################
    ## Input_Slider
    ################################################
    input_slider.upstairs_heat:
      icon: mdi:nest-thermostat

    input_slider.upstairs_ac:
      icon: mdi:nest-thermostat


#####################################################################
### Group
#####################################################################
group:
  Upstairs Climate:
    entities:
      - sensor.upstairs_thermostat_temperature
      - sensor.hvac_upstairs_op_state
      - sensor.hvac_upstairs_mode
      - sensor.us_climate_control
      - sensor.hvac_upstairs_fan
      - sensor.upstairs_thermostat_statistics_mean

  Upstairs Heating:
    entities:
      - sensor.hvac_upstairs_heat_setpoint
      - input_slider.us_low
      - input_slider.upstairs_heat
      - script.heat_upstairs_60min

  Upstairs Cooling:
    entities:
      - sensor.hvac_upstairs_ac_setpoint
      - input_slider.us_high
      - input_slider.upstairs_ac
      - script.cool_upstairs_60min


#####################################################################
### Input Slider
#####################################################################
input_slider:
  ### Upstairs Heat Temp Adjustment
  upstairs_heat:
    name: "Upstairs Heat"
    initial: 68
    min: 60
    max: 90
    step: 1

  ### Upstairs AC Temp Adjustment
  upstairs_ac:
    name: "Upstairs AC"
    initial: 83
    min: 60
    max: 90
    step: 1

  ### Upstairs Low Temp trigger - "at what temp is COLD triggered?"
  us_low:
    name: "Upstairs Low"
    initial: 69
    min: 60
    max: 90
    step: 1

  ### Upstairs High Temp trigger - "at what temp is HOT triggered?"
  us_high:
    name: "Upstairs High"
    initial: 83
    min: 60
    max: 90
    step: 1


#####################################################################
### Sensor
#####################################################################
sensor:
## Median Temperature Upstairs
  - platform: statistics
    entity_id: sensor.upstairs_thermostat_temperature
    name: Upstairs Thermostat Statistics

  - platform: template
    sensors:
      hvac_upstairs_mode:
        friendly_name: "Upstairs Thermostat Mode"
        value_template: "{{ states('climate.upstairs_thermostat_cooling_1') }}"

      hvac_upstairs_op_state:
        friendly_name: "Upstairs HVAC State"
        value_template: "{{ (states.climate.upstairs_thermostat_cooling_1.attributes|default({})).operating_state|default('unknown') }}"

      hvac_upstairs_fan:
        friendly_name: "Upstairs HVAC Fan"
        value_template: "{{ (states.climate.upstairs_thermostat_cooling_1.attributes|default({})).fan_state|default('unknown') }}"

      hvac_upstairs_ac_setpoint:
        friendly_name: "Upstairs AC Setpoint"
        value_template: "{{ (states.climate.upstairs_thermostat_cooling_1.attributes|default({})).temperature|default('unknown') }}"

      hvac_upstairs_heat_setpoint:
        friendly_name: "Upstairs Heat Setpoint"
        value_template: "{{ (states.climate.upstairs_thermostat_heating_1.attributes|default({})).temperature|default('unknown') }}"

## Upstairs Climate Control
  - platform: template
    sensors:
      us_climate_control:
        friendly_name: "Upstairs Climate Control"
        value_template: >-
          {% set temperature = states('sensor.upstairs_thermostat_temperature')|float(none) %}
          {% set us_low = states.input_slider.us_low.state|default(68)|float %}
          {% set us_high = states.input_slider.us_high.state|default(81)|float %}
          {% if temperature is none %}
            {{ states('sensor.upstairs_thermostat_temperature') }}
          {% elif temperature < us_low %}
            Cold
          {% elif temperature > us_high %}
            Hot
          {% else %}
            Comfy
          {% endif %}

#####################################################################
### Script
#####################################################################
script:
  cool_upstairs_60min:
    sequence:
      - service: climate.set_operation_mode
        entity_id: climate.upstairs_thermostat_cooling_1
        data:
          operation_mode: 'Cool'

      - service: input_slider.select_value
        data_template:
          entity_id: input_slider.upstairs_ac
          value: 75

      - service: notify.ios_iphwn666
        data:
          title: "HVAC Event"
          message: "Cooling Upstairs for 1 hour starting at {{ states('sensor.date__time') }}"

      - delay: 01:00

      - service: input_slider.select_value
        data_template:
          entity_id: input_slider.upstairs_ac
          value: 83

## Heat Upstairs 60 min
  heat_upstairs_60min:
    sequence:
      - service: climate.set_operation_mode
        entity_id: climate.upstairs_thermostat_heating_1
        data:
          operation_mode: 'Heat'

      - service: input_slider.select_value
        data_template:
          entity_id: input_slider.upstairs_heat
          value: 86

      - service: notify.ios_iphwn666
        data:
          title: "HVAC Event"
          message: "Upstairs Quick Heat started at {{ states('sensor.date__time') }}"

      - delay: 01:00

      - service: input_slider.select_value
        data_template:
          entity_id: input_slider.upstairs_heat
          value: 66

# automation: (see automations folder)
