############################################################################
#    @package          :     climate_downstairs
#    @description      :     climate_downstairs, and associated automations, scenes, etc.
############################################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'climate_downstairs'

      contained: &contained
        <<: *customize
        haaska_hidden: true
        homebridge_hidden: true

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

      hidden: &hidden
        <<: *contained
        hidden: true

    ################################################
    ## Group
    ################################################
    group.downstairs_climate:
      <<: *contained
      #order: 1

    group.downstairs_ecobee:
      <<: *contained
      #order: 1

    script.ecobee_home:
      <<: *contained
      friendly_name: "Ecobee Home"
      entity_picture: /local/ecobee.png

    script.ecobee_away:
      <<: *contained
      friendly_name: "Ecobee Away"
      entity_picture: /local/ecobee.png

    script.ecobee_sleep:
      <<: *contained
      friendly_name: "Ecobee Sleep"
      entity_picture: /local/ecobee.png

    script.ecobee_resume:
      <<: *contained
      friendly_name: "Ecobee Resume"
      entity_picture: /local/ecobee.png

    sensor.ds_avg_temp:
      <<: *contained
      icon: mdi:chart-areaspline

    sensor.downstairs_humidity:
      <<: *contained
      icon: mdi:water-percent

    sensor.front_entry_fibaro_multisensor_temperature:
      <<: *contained
      friendly_name: "Front Entry Temperature"
      icon: mdi:thermometer

    sensor.broadlink_sensor_temperature:
      <<: *contained
      friendly_name: "Entryway Temperature"
      icon: mdi:thermometer


#####################################################################
### Group
#####################################################################
group:
  Downstairs Climate:
    entities:
      - sensor.ds_avg_temp
      - climate.downstairs
      - sensor.downstairs_temperature
      - sensor.living_room_temperature
      - sensor.office_temperature
      - sensor.front_entry_fibaro_multisensor_temperature
      - sensor.broadlink_sensor_temperature
      - sensor.downstairs_humidity

  Downstairs Ecobee:
    control: hidden
    entities:
      - script.ecobee_home
      - script.ecobee_away
      - script.ecobee_sleep
      - script.ecobee_resume


#####################################################################
### Ecobee
#####################################################################
ecobee:
  api_key: !secret ecobee_api_key
  hold_temp: True


#####################################################################
### Sensor
#####################################################################
sensor:
  - platform: template
    sensors:
      ds_avg_temp:
        friendly_name: "Downstairs Average Temperature"
        unit_of_measurement: "F"
        value_template: >-
          {{ ((float(states.sensor.downstairs_temperature.state) + float(states.sensor.living_room_temperature.state) + float(states.sensor.office_temperature.state) + float(states.sensor.front_entry_fibaro_multisensor_temperature.state) + float(states.sensor.broadlink_sensor_temperature.state)) / 5) | round(1) }}


  ################################################
  ## Broadlink RM 2 Pro
  ################################################
  - platform: broadlink
    host: !secret broadlink_ip
    mac: !secret broadlink_mac
    monitored_conditions:
      - 'temperature'


#####################################################################
### Script
#####################################################################
script:
  ecobee_sleep:
    sequence:
      - service: climate.set_hold_mode
        data:
          entity_id: climate.downstairs
          hold_mode: 'sleep'

  ecobee_home:
    sequence:
      - service: climate.set_hold_mode
        data:
          entity_id: climate.downstairs
          hold_mode: 'home'

  ecobee_away:
    sequence:
      - service: climate.set_hold_mode
        data:
          entity_id: climate.downstairs
          hold_mode: 'away'

  ecobee_resume:
    sequence:
      - service: climate.ecobee_resume_program
        data:
          entity_id: climate.downstairs
          resume_all: 'true'


#####################################################################
### Automation
#####################################################################
automation:
  - alias: downstairs cooling schedule
    trigger:
      - platform: time
        at: '06:00:00'

    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: group.all_devices
          state: 'home'

        - condition: state
          entity_id: input_boolean.visitor_mode
          state: 'on'

    action:
      - service: climate.set_hold_mode
        data:
          entity_id: climate.downstairs
          hold_mode: 'home'


  - alias: downstairs climate sleep mode
    trigger:
      - platform: state
        entity_id: script.bedtime
        from: 'off'
        to: 'on'

      - platform: state
        entity_id: input_boolean.after_hours
        from: 'off'
        to: 'on'

    action:
      - service: climate.set_hold_mode
        data:
          entity_id: climate.downstairs
          hold_mode: 'sleep'
