############################################################################
#    @package          :     climate_upstairs
#    @description      :     climate_upstairs, and associated automations, scenes, etc.
############################################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'climate_upstairs'

      contained: &contained
        <<: *customize
        haaska_hidden: true
        homebridge_hidden: true

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

      hidden: &hidden
        <<: *contained
        hidden: true

    ################################################
    ## Group
    ################################################
    group.upstairs_climate:
      <<: *contained
      order: 3

    group.upstairs_ecobee:
      <<: *contained
      order: 4

    script.ecobee_us_home:
      <<: *contained
      friendly_name: "Ecobee Upstairs Home"
      entity_picture: /local/ecobee.png

    script.ecobee_us_away:
      <<: *contained
      friendly_name: "Ecobee Upstairs Away"
      entity_picture: /local/ecobee.png

    script.ecobee_us_evening:
      <<: *contained
      friendly_name: "Ecobee Upstairs Evening"
      entity_picture: /local/ecobee.png

    script.ecobee_us_sleep:
      <<: *contained
      friendly_name: "Ecobee Upstairs Sleep"
      entity_picture: /local/ecobee.png

    script.ecobee_us_resume:
      <<: *contained
      friendly_name: "Ecobee Upstairs Resume"
      entity_picture: /local/ecobee.png

    sensor.us_avg_temp:
      <<: *contained
      icon: mdi:chart-areaspline

    sensor.us_fan_state:
      <<: *contained
      icon: mdi:fan

    sensor.upstairs_humidity:
      <<: *contained
      icon: mdi:water-percent

    sensor.us_climate_mode:
      <<: *contained
      icon: mdi:nest-thermostat


#####################################################################
### Group
#####################################################################
group:
  Upstairs Climate:
    entities:
      - climate.upstairs
      - sensor.upstairs_temperature
      - sensor.kids_room_temperature
      - sensor.guest_room_temperature
      - sensor.us_avg_temp
      - sensor.upstairs_humidity

  Upstairs Ecobee:
    control: hidden
    entities:
      - sensor.us_climate_mode
      - sensor.us_fan_state
      - script.ecobee_us_home
      - script.ecobee_us_away
      - script.ecobee_us_sleep
      - script.ecobee_us_resume


#####################################################################
### Sensor
#####################################################################
sensor:
  - platform: template
    sensors:
      us_avg_temp:
        friendly_name: "Upstairs Average Temperature"
        unit_of_measurement: "F"
        value_template: >-
          {{ ((float(states.sensor.upstairs_temperature.state) + float(states.sensor.kids_room_temperature.state) + float(states.sensor.guest_room_temperature.state)) / 3) | round(1) }}

  - platform: template
    sensors:
      us_climate_mode:
        friendly_name: "Upstairs HVAC Mode"
        value_template: "{{ (states.climate.upstairs.attributes|default({})).mode|default('unknown') }}"

  - platform: template
    sensors:
      us_fan_state:
        friendly_name: "Upstairs HVAC Fan State"
        value_template: "{{ (states.climate.upstairs.attributes|default({})).fan|default('unknown') }}"


#####################################################################
### Script
#####################################################################
script:
  ecobee_us_home:
    sequence:
      - service: climate.set_hold_mode
        data:
          entity_id: climate.upstairs
          hold_mode: 'home'

  ecobee_us_away:
    sequence:
      - service: climate.set_hold_mode
        data:
          entity_id: climate.upstairs
          hold_mode: 'away'

  ecobee_us_sleep:
    sequence:
      - service: climate.set_hold_mode
        data:
          entity_id: climate.upstairs
          hold_mode: 'sleep'

  ecobee_us_resume:
    sequence:
      - service: climate.ecobee_resume_program
        data:
          entity_id: climate.upstairs
          resume_all: 'true'


#####################################################################
### Automation
#####################################################################
automation:
  ### Home Mode Weekdays
  - alias: Climate Upstairs Home Schedule Weekdays
    initial_state: 'on'
    trigger:
      - platform: time
        at: '07:00:00'

    condition:
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'

      - condition: or
        conditions:
          - condition: state
            entity_id: group.all_devices
            state: 'home'

          - condition: state
            entity_id: input_boolean.visitor_mode
            state: 'on'

    action:
      - service: climate.set_hold_mode
        data:
          entity_id: climate.upstairs
          hold_mode: 'home'


  ### Home Mode Weekends
  - alias: Climate Upstairs Home Schedule Weekends
    initial_state: 'on'
    trigger:
      - platform: time
        at: '09:00:00'

    condition:
      - condition: time
        weekday:
          - sat
          - sun

      - condition: or
        conditions:
          - condition: state
            entity_id: group.all_devices
            state: 'home'

          - condition: state
            entity_id: input_boolean.visitor_mode
            state: 'on'

    action:
      - service: climate.set_hold_mode
        data:
          entity_id: climate.upstairs
          hold_mode: 'home'


  ### Sleep Mode Weekdays
  - alias: Climate Upstairs Sleep Schedule Weekdays
    initial_state: 'on'
    trigger:
      - platform: time
        at: '20:00:00'

    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - sun

      - condition: or
        conditions:
          - condition: state
            entity_id: group.all_devices
            state: 'home'

          - condition: state
            entity_id: input_boolean.visitor_mode
            state: 'on'

    action:
      - service: climate.set_hold_mode
        data:
          entity_id: climate.upstairs
          hold_mode: 'sleep'


  ### Sleep Mode Weekends
  - alias: Climate Upstairs Sleep Schedule Weekends
    initial_state: 'on'
    trigger:
      - platform: time
        at: '21:00:00'

    condition:
      - condition: time
        weekday:
          - fri
          - sat

      - condition: or
        conditions:
          - condition: state
            entity_id: group.all_devices
            state: 'home'

          - condition: state
            entity_id: input_boolean.visitor_mode
            state: 'on'

    action:
      - service: climate.set_hold_mode
        data:
          entity_id: climate.upstairs
          hold_mode: 'sleep'


  ### Peak Hours Mode
  - alias: Climate Upstairs Peak Hours
    initial_state: 'on'
    trigger:
      - platform: time
        at: '12:00:00'

    action:
      - service: climate.set_hold_mode
        data:
          entity_id: climate.upstairs
          hold_mode: 'away'
