############################################################################
#    @package          :     climate_global
#    @description      :     global climate automations.
############################################################################
automation:
  ### Set Climate on away
  - alias: Climate Global Away Mode
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: group.all_devices
        from: 'home'
        to: 'not_home'
        for:
          minutes: 15

    condition:
      - condition: state
        entity_id: input_boolean.visitor_mode
        state: 'off'

    action:
    ########################
    ### Set Downstairs Away
    ########################
      - service: climate.set_hold_mode
        data:
          entity_id: climate.downstairs
          hold_mode: 'away'

    ########################
    ### Set Upstairs Away
    ########################
      - service: climate.set_hold_mode
        data:
          entity_id: climate.upstairs
          hold_mode: 'away'


  ### Set Temperature Thresholds upon return
  - alias: Climate Global Resume
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: group.all_devices
      from: 'not_home'
      to: 'home'
      for:
        minutes: 2

    action:
    ########################
    ### Set Downstairs Resume
    ########################
      - service: climate.ecobee_resume_program
        data:
          entity_id: climate.downstairs
          resume_all: 'true'

    ########################
    ### Set Upstairs Resume
    ########################
      - service: climate.ecobee_resume_program
        data:
          entity_id: climate.upstairs
          resume_all: 'true'
