############################################################################
#    @package          :     master_bed_bath
#    @description      :     master bedrrom, master bath, and associated automations, scenes, etc.
############################################################################
homeassistant:
  customize:
    group.master_bedroom:
      haaska_name: "Master Bedroom Lights"
      order: 6

    cover.somfy_unknown_type5a52_id5402_level_37_0:
      friendly_name: "Master Bath Shades"
      homebridge_cover_type: rollershutter
      icon: mdi:blinds

## Master Bath Roller Shade State (hidden)
    cover.somfy_unknown_type5a52_id5402_switch_37_0:
      friendly_name: "Bathroom Shade State"
      haaska_hidden: true
      homebridge_hidden: true
      icon: mdi:blinds

    light.ge_12724_3way_dimmer_switch_level_8_0:
      friendly_name: "Master Bedroom Chandelier"
      haaska_name: "Master Bedroom Chandelier"
      icon: mdi:ceiling-light

    light.under_bed_lights:
      friendly_name: "Bed Lights"
      icon: mdi:led-on

    light.master_sitting_lamp:
      haaska_hidden: true
      icon: mdi:lamp

    switch.humidifier:
      friendly_name: "Humidifier"
      icon: mdi:cup-water

    script.mbr_night_light:
      icon: mdi:weather-night

    script.master_bedroom_night_time:
      friendly_name: "Master Bedroom Night Time"
      icon: mdi:weather-night

    script.mbr_fan_speed_step_low:
      friendly_name: "Master Bedroom Fan Auto Low"
      icon: mdi:fan
      haaska_hidden: true

    script.mbr_fan_speed_step_high:
      friendly_name: "Master Bedroom Fan Auto High"
      icon: mdi:fan
      haaska_hidden: true


group:
  Master Bedroom:
    control: hidden
    entities:
      - script.master_bedroom_night_time
      - script.mbr_night_light
      - input_select.master_bedroom_fan_speed
      - light.ge_12724_3way_dimmer_switch_level_8_0
      - light.under_bed_lights
      - light.master_sitting_lamp
      - input_select.mbr_under_bed_color
      - input_select.mbr_under_bed_effect
      - input_select.mbr_under_bed_strobe
      - switch.master_bedroom_fan_light
      #- input_select.master_bedroom_fan_options
      - script.mbr_fan_speed_step_low
      - script.mbr_fan_speed_step_high
      - switch.master_bedroom_fan_delay
      - switch.humidifier
## Master Bath Somfy
      - cover.somfy_unknown_type5a52_id5402_level_37_0
      #- cover.somfy_unknown_type5a52_id5402_switch_37_0


light:
  - platform: flux_led
    devices:
      !secret under_bed_light_master:
        name: "under_bed_lights"
        mode: rgb


script:
#####################################################################
### Master Bedroom - Night Mode
#####################################################################
  master_bedroom_night_time:
    sequence:
  ### Set master bedroom chandelier to dim
    - service: light.turn_on
      entity_id: light.ge_12724_3way_dimmer_switch_level_8_0
      data:
        brightness: 65

    - service: light.turn_on
      entity_id: light.master_sitting_lamp
      data:
        brightness: 50
        transition: 3

  ### Turn on the under-bed lights
    - service: light.turn_on
      data:
        entity_id: light.under_bed_lights
        rgb_color: [0,55,55]

#####################################################################
### Master Bedroom Night Light; 6 min timer
#####################################################################
  mbr_night_light:
    alias: "Night Light"
    sequence:
    - service: light.turn_on
      data:
        entity_id: light.under_bed_lights
        rgb_color: [0,60,60]

    - service: light.turn_on
      entity_id: light.master_sitting_lamp
      data:
        brightness: 40
        transition: 5

    - delay:
        minutes: 4

    - service: light.turn_off
      entity_id: light.master_sitting_lamp
      data:
        transition: 10

    - delay:
        minutes: 1

    - service: light.turn_off
      data:
        entity_id: light.under_bed_lights

#####################################################################
### Start the Master Bedroom Fan on low and then step it down 
#####################################################################
  mbr_fan_speed_step_low:
    sequence:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.master_bedroom_fan_speed
          option: off

      - delay: 2

      - service: input_select.select_option
        data_template:
          entity_id: input_select.master_bedroom_fan_speed
          option: 2

      - delay:
          hours: 3

      - service: input_select.select_option
        data_template:
          entity_id: input_select.master_bedroom_fan_speed
          option: 1

#####################################################################
### Start the Master Bedroom Fan on high and then step it down 
#####################################################################
  mbr_fan_speed_step_high:
    sequence:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.master_bedroom_fan_speed
          option: off

      - delay: 2

      - service: input_select.select_option
        data_template:
          entity_id: input_select.master_bedroom_fan_speed
          option: 4

      - delay:
          hours: 2

      - service: input_select.select_option
        data_template:
          entity_id: input_select.master_bedroom_fan_speed
          option: 2


automation:
#####################################################################
### MASTER BATH - Raise Shade
#####################################################################
  - alias: master bath shade raised schedule
    hide_entity: True
    trigger:
      - platform: time
        at: '11:00:00'

    action:
      - service: cover.open_cover
        entity_id: cover.somfy_unknown_type5a52_id5402_level_37_0

#####################################################################
### MASTER BATH - Lower Shade
#####################################################################
  - alias: master bath shade lowered schedule
    hide_entity: True
    trigger:
      - platform: sun
        event: sunset
        offset: '00:15:00'

    action:
      - service: cover.close_cover
        entity_id: cover.somfy_unknown_type5a52_id5402_level_37_0

######################################################################
#### Master Bedroom Fan Speed
######################################################################
  - alias: master_bedroom_fan_speed_selector
    trigger:
      - platform: state
        entity_id: input_select.master_bedroom_fan_speed

    condition:
      - condition: template
        value_template: "{{ trigger.to_state.state != 'Select an option...' }}"

    action:
      # Turn the corresponding switch on to send the fan speed command
      - service: switch.turn_on
        data_template:
          entity_id: "switch.master_bedroom_fan_{{ trigger.to_state.state|lower|replace(' ', '_') }}"

      # Reset the Input Select to "Select an option..."
      - service: input_select.select_option
        data_template:
          entity_id: "{{ trigger.to_state.entity_id }}"
          option: Select an option...

######################################################################
#### Master Bedroom Fan Options
######################################################################
  - alias: master_bedroom_fan_option_selector
    trigger:
      - platform: state
        entity_id: input_select.master_bedroom_fan_options

    condition:
      - condition: template
        value_template: "{{ trigger.to_state.state != 'Select an option...' }}"

    action:
      # Turn the corresponding switch on to send the fan speed command
      - service: switch.turn_on
        data_template:
          entity_id: "switch.master_bedroom_fan_{{ trigger.to_state.state|lower|replace(' ', '_') }}"

      # Reset the Input Select to "Select an option..."
      - service: input_select.select_option
        data_template:
          entity_id: "{{ trigger.to_state.entity_id }}"
          option: Select an option...

######################################################################
#### Master Bedroom Fan Auto High
######################################################################
  - alias: master_bedroom_fan_auto_high
    trigger:
      - platform: state
        entity_id: script.master_bedroom_night_time
        to: 'on'

    condition:
      - condition: numeric_state
        entity_id: sensor.2gig_technologies_ct101_thermostat_iris_temperature_42_1
        above: 82

    action:
  ### Turn the ceiling fan on auto-high
      - service: script.turn_on
        entity_id: script.mbr_fan_speed_step_high

######################################################################
#### Humidifier
######################################################################
  - alias: Turn off Humidifier
    hide_entity: True
    trigger:
      platform: time
      at: '06:45:00'

    condition:
      condition: state
      entity_id: switch.humidifier
      state: 'on'

    action:
      service: switch.turn_off
      entity_id: switch.humidifier
