############################################################################
#    @package          :     master_bedroom_fan
#    @description      :     master bedrrom ceiling fan and associated automations, scenes, etc.
############################################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'master_bedroom_fan'

      contained: &contained
        <<: *customize
        haaska_hidden: true
        homebridge_hidden: true

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

      hidden: &hidden
        <<: *contained
        hidden: true

    ################################################
    ## Group
    ################################################
    group.master_bedroom_fan:
      <<: *contained
      order: 2

    group.mbr_fan_speed:
      <<: *hidden

    ################################################
    ## Switch
    ################################################
    switch.master_bedroom_fan:
      friendly_name: "Master Bedroom Fan"
      icon: mdi:fan

    switch.master_bedroom_fan_light:
      assumed_state: false
      friendly_name: "Master Bedroom Fan Light"
      haaska_name: "Bedroom Fan Light"
      icon: mdi:ceiling-light

    switch.master_bedroom_fan_1:
      <<: *contained

    switch.master_bedroom_fan_2:
      <<: *contained

    switch.master_bedroom_fan_3:
      <<: *contained

    switch.master_bedroom_fan_4:
      <<: *contained

    switch.master_bedroom_fan_5:
      <<: *contained

    switch.master_bedroom_fan_6:
      <<: *contained

    switch.master_bedroom_fan_random:
      <<: *contained

    switch.master_bedroom_fan_vacation:
      <<: *contained

    switch.master_bedroom_fan_delay:
      <<: *contained

    switch.master_bedroom_fan_summer_mode:
      <<: *contained

    ################################################
    ## Script
    ################################################
    script.mbr_fan_speed_step_low:
      <<: *contained
      friendly_name: "Master Bedroom Fan Auto Low"
      icon: mdi:fan

    script.mbr_fan_speed_step_high:
      <<: *contained
      friendly_name: "Master Bedroom Fan Auto High"
      icon: mdi:fan


#####################################################################
### Group
#####################################################################
group:
  Master Bedroom Fan:
    control: hidden
    entities:
      - switch.master_bedroom_fan
      - switch.master_bedroom_fan_light
      - input_select.master_bedroom_fan_speed
      - script.mbr_fan_speed_step_low
      - script.mbr_fan_speed_step_high

  MBR Fan Speed:
    entities:
      - switch.master_bedroom_fan_1
      - switch.master_bedroom_fan_2
      - switch.master_bedroom_fan_3
      - switch.master_bedroom_fan_4
      - switch.master_bedroom_fan_5
      - switch.master_bedroom_fan_6


#####################################################################
### Input Select
#####################################################################
input_select:
  master_bedroom_fan_speed:
    name: Master Bedroom Fan Speed
    initial: "Select an option..."
    options:
      - "Select an option..."
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
      - "6"
      - "Random"


#####################################################################
### Script
#####################################################################
script:
  mbr_fan_speed_step_low:
    sequence:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.master_bedroom_fan_speed
          option: off

      - delay: 2

      - service: input_select.select_option
        data_template:
          entity_id: input_select.master_bedroom_fan_speed
          option: 2

      - delay:
          hours: 3

      - service: input_select.select_option
        data_template:
          entity_id: input_select.master_bedroom_fan_speed
          option: 1


  mbr_fan_speed_step_high:
    sequence:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.master_bedroom_fan_speed
          option: off

      - delay: 2

      - service: input_select.select_option
        data_template:
          entity_id: input_select.master_bedroom_fan_speed
          option: 4

      - delay:
          hours: 2

      - service: input_select.select_option
        data_template:
          entity_id: input_select.master_bedroom_fan_speed
          option: 2


#####################################################################
### Automation
#####################################################################
automation:
  ## turn the master bed fan off at noon each day
  - alias: turn off master bedroom fan
    initial_state: 'on'
    trigger:
      - platform: time
        at: '12:00:00'

    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.master_bedroom_fan_speed
          option: Off


  ## select a fan speed
  - alias: master_bedroom_fan_speed_selector
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_select.master_bedroom_fan_speed

    condition:
      - condition: template
        value_template: "{{ trigger.to_state.state != 'Select an option...' }}"

    action:
      # Reset fan switch states
      - service: homeassistant.turn_off
        data:
          entity_id: group.mbr_fan_speed

      # Turn on the corresponding fan speed switch
      - service: switch.turn_on
        data_template:
          entity_id: "switch.master_bedroom_fan_{{ trigger.to_state.state|lower|replace(' ', '_') }}"

      # Reset the Input Select to "Select an option..."
      - service: input_select.select_option
        data_template:
          entity_id: "{{ trigger.to_state.entity_id }}"
          option: Select an option...


  ## select fan options
  - alias: master_bedroom_fan_option_selector
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_select.master_bedroom_fan_options

    condition:
      - condition: template
        value_template: "{{ trigger.to_state.state != 'Select an option...' }}"

    action:
      # Turn the corresponding switch on to send the fan speed command
      - service: switch.turn_on
        data_template:
          entity_id: "switch.master_bedroom_fan_{{ trigger.to_state.state|lower|replace(' ', '_') }}"

      # Reset the Input Select to "Select an option..."
      - service: input_select.select_option
        data_template:
          entity_id: "{{ trigger.to_state.entity_id }}"
          option: Select an option...

  ## fan auto-high
  - alias: master_bedroom_fan_auto_high
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: script.master_bedroom_night_time
        to: 'on'

    condition:
      - condition: numeric_state
        entity_id: sensor.upstairs_thermostat_temperature
        above: 82

    action:
      - service: script.turn_on
        entity_id: script.mbr_fan_speed_step_high
