#####################################################################
#    @package          :     media_players
#    @description      :     media players and associated automations, scenes, etc.
#####################################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'media_players'

      contained: &contained
        <<: *customize
        haaska_hidden: true
        homebridge_hidden: true

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

      hidden: &hidden
        <<: *contained
        hidden: true

    ################################################
    ## Group
    ################################################
    group.media_players:
      <<: *contained

    ################################################
    ## Media Player
    ################################################
    media_player.kodi_office:
      <<: *contained
      friendly_name: "Office Kodi"

    media_player.kodi_bedroom:
      <<: *contained
      friendly_name: "Bedroom Kodi"

    media_player.apple_tv:
      <<: *contained
      friendly_name: "Apple TV"


#####################################################################
### Group
#####################################################################
group:
  Media Players:
    entities:
      - media_player.kodi_office
      - media_player.apple_tv
    #  - media_player.rnmcast


#####################################################################
### Media Player
#####################################################################
media_player:
  - platform: kodi
    host: !secret kodi_office
    port: !secret kodi_port
    name: kodi_office
    username: !secret kodi_user
    password: !secret kodi_password

  - platform: kodi
    host: !secret kodi_bedroom
    port: !secret kodi_port
    name: kodi_bedroom
    username: !secret kodi_user
    password: !secret kodi_password

  - platform: apple_tv
    host: !secret appletv_host
    name: apple_tv
    login_id: !secret appletv_login_id
