#####################################################################
#    @package          :     Minimotes
#    @description      :     Minimotes and associated automations, etc.
#####################################################################


#####################################################################
### Automation
#####################################################################
automation:
  ### Aeotec zwave Minimote #1: zwave.living_room_Minimote
  - alias: Minimote 1 Button 1 Short
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.living_room_Minimote
          scene_id: 1

    action:
      - service: scene.turn_on
        entity_id: scene.living_room_normal

  ###
  - alias: Minimote 1 Button 1 Long
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.living_room_Minimote
          scene_id: 2

    action:
      - service: scene.turn_on
        entity_id: scene.living_room_bright

  ###
  - alias: Minimote 1 Button 2 Short
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.living_room_Minimote
          scene_id: 3

    action:
      - service: scene.turn_on
        entity_id: scene.movie_time

      - service: light.turn_off
        entity_id: light.kitchen_lights_level

  ###
  - alias: Minimote 1 Button 2 Long
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.living_room_Minimote
          scene_id: 4

    action:
      - service: scene.turn_on
        entity_id: scene.living_room_dim

  ###
  - alias: Minimote 1 Button 3 Short
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.living_room_Minimote
          scene_id: 5

    action:
      - service: light.turn_on
        data:
          entity_id: light.kitchen_lights_level
          transition: 5
          brightness: 150

  ###
  - alias: Minimote 1 Button 3 Long
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.living_room_Minimote
          scene_id: 6

    action:
      - service: light.turn_on
        data:
          entity_id: light.kitchen_lights_level
          transition: 5
          brightness: 255

  ###
  - alias: Minimote 1 Button 4 Short
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.living_room_Minimote
          scene_id: 7

    action:
      - service: light.turn_off
        data:
          entity_id: light.kitchen_lights_level

  ###
  - alias: Minimote 1 Button 4 Long
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.living_room_Minimote
          scene_id: 8

    action:
      - service: script.bedtime


  ### Aeotec zwave Minimote #2: zwave.master_bedroom_Minimote
  - alias: Minimote 2 Button 1 Short
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.master_bedroom_Minimote
          scene_id: 1

    action:
      - service: script.master_bedroom_night_time

      - service: light.turn_on
        data:
          entity_id: light.under_bed_lights

  ###
  - alias: Minimote 2 Button 1 Long
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.master_bedroom_Minimote
          scene_id: 2

    action:
      - service: light.turn_off
        data:
          entity_id: light.master_bedroom_chandelier_level

      - service: light.turn_off
        data:
          entity_id: light.under_bed_lights

  ###
  - alias: Minimote 2 Button 2 Short
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.master_bedroom_Minimote
          scene_id: 3

    action:
      - service: script.mbr_night_light

  ###
  - alias: Minimote 2 Button 2 Long
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.master_bedroom_Minimote
          scene_id: 4

    action:
      - service: scene.turn_on
        data:
          entity_id: script.bedtime

  ###
  - alias: Minimote 2 Button 3 Short
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.master_bedroom_Minimote
          scene_id: 5

    action:
      - service: scene.turn_on
        data:
          entity_id: scene.early_morning

  ###
  - alias: Minimote 2 Button 3 Long
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.master_bedroom_Minimote
          scene_id: 6

    action:
      - service: scene.turn_on
        data:
          entity_id: script.cool_upstairs_120min

  ###
  - alias: Minimote 2 Button 4 Short
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.master_bedroom_Minimote
          scene_id: 7

    action:
      - service: script.mbr_fan_speed_step_low

  ###
  - alias: Minimote 2 Button 4 Long
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.master_bedroom_Minimote
          scene_id: 8

    action:
      - service: script.mbr_fan_speed_step_high


  ### Aeotec zwave Minimote #3: aeotec_dsa03202_Minimote_31
