#####################################################################
#    @package          :     notify
#    @description      :     notifications and alerting components
#####################################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'notify'

      contained: &contained
        <<: *customize
        haaska_hidden: true
        homebridge_hidden: true

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

      hidden: &hidden
        <<: *contained
        hidden: true


#####################################################################
### Notify
#####################################################################
notify:
  - platform: pushbullet
    name: pushbullet
    api_key: !secret pushbullet_api_key

  - platform: ecobee
    name: downstairs_ecobee

  - platform: ecobee
    name: upstairs_ecobee

#####################################################################
### iOS
#####################################################################
ios:
  push:
    categories:
      - name: Alarm
        identifier: 'ALARM'
        actions:
          - identifier: 'SOUND_ALARM'
            title: 'Sound Alarm'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: yes
            behavior: 'default'
          - identifier: 'SILENCE_ALARM'
            title: 'Silence Alarm'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: no
            behavior: 'textInput'
            textInputButtonTitle: 'Silencio!'
            textInputPlaceholder: 'Placeholder'
