#####################################################################
#    @package          :     patio
#    @description      :     patio, audio, and associated automations, scenes, etc.
#####################################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'patio'

      contained: &contained
        <<: *customize
        haaska_hidden: true
        homebridge_hidden: true

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

      hidden: &hidden
        <<: *contained
        hidden: true

    ################################################
    ## Group
    ################################################
    group.exterior:
      haaska_hidden: true

    group.pool:
      haaska_hidden: true

    group.yard:
      haaska_name: "Backyard"

    group.exterior_lights:
      haaska_name: "Exterior Lights"

    ################################################
    ## Switch
    ################################################
    switch.patio_party_lights_switch:
      friendly_name: "Party Lights"
      icon: mdi:glass-mug

    switch.patio_lights_switch:
      friendly_name: "Patio Lights"
      icon: mdi:white-balance-incandescent

    switch.fountains_switch:
      friendly_name: "Fountains"
      icon: mdi:beach


#####################################################################
### Group
#####################################################################
group:
  Exterior Lights:
    entities:
      - switch.patio_lights_switch
      - switch.patio_party_lights_switch

  Yard:
    control: hidden
    entities:
      - switch.patio_lights_switch
      - switch.patio_party_lights_switch
      - switch.fountains_switch
      ## outdoor speakers
      - switch.switch_one


#####################################################################
### Automation
#####################################################################
automation:
### FOUNTAINS ON
  - alias: turn on fountains
    trigger:
      - platform: sun
        event: sunrise
        offset: '01:30:00'

      - platform: state
        entity_id: group.all_devices
        from: 'not_home'
        to: 'home'

    condition:
      - condition: numeric_state
        entity_id: sensor.pws_wind_mph
        below: 10

      - condition: state
        entity_id: input_boolean.rain
        state: 'off'

      - condition: sun
        before: sunset

      - condition: state
        entity_id: group.all_devices
        state: 'home'

    action:
      - service: switch.turn_on
        data:
          entity_id: switch.fountains_switch


### FOUNTAINS OFF
  - alias: turn off fountains
    hide_entity: True
    trigger:
      - platform: sun
        event: sunset
        offset: '00:05:00'

      - platform: state
        entity_id: input_boolean.rain
        from: 'off'
        to: 'on'
        for:
          minutes: 5

    condition:
      - condition: state
        entity_id: switch.fountains_switch
        state: 'on'

    action:
      - service: switch.turn_off
        data:
          entity_id: switch.fountains_switch


### Turn off the Party Lights - Weekdays
  - alias: turn off party lights weekdays
    trigger:
      platform: time
      at: '00:00:00'

    condition:
      - condition: time
        weekday:
          - sun
          - mon
          - tue
          - wed
          - thu

      - condition: state
        entity_id: switch.patio_party_lights_switch
        state: 'on'

    action:
  # outdoor Party lights
      - service: switch.turn_off
        entity_id: switch.patio_party_lights_switch


### Turn off the Party Lights - Weekends
  - alias: turn off party lights weekends
    trigger:
      platform: time
      at: '02:00:00'

    condition:
      - condition: time
        weekday:
          - sat
          - sun

      - condition: state
        entity_id: switch.patio_party_lights_switch
        state: 'on'

    action:
      - service: switch.turn_off
        entity_id: switch.patio_party_lights_switch
