#####################################################################
#    @package          :     patio
#    @description      :     patio, fountains, and associated automations, scenes, etc.
#####################################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'patio'

      contained: &contained
        <<: *customize
        haaska_hidden: true
        homebridge_hidden: true

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

      hidden: &hidden
        <<: *contained
        hidden: true

    ################################################
    ## Group
    ################################################
    group.yard:
      <<: *exposed
      haaska_name: "Backyard"
      order: 1

    group.exterior_lights:
      <<: *exposed
      haaska_name: "Exterior Lights"

    ################################################
    ## Switch
    ################################################
    switch.patio_party_lights_switch:
      friendly_name: "Party Lights"
      icon: mdi:glass-mug

    switch.patio_lights_switch:
      friendly_name: "Patio Lights"
      icon: mdi:white-balance-incandescent


#####################################################################
### Group
#####################################################################
group:
  Exterior Lights:
    entities:
      - switch.patio_lights_switch
      - switch.patio_party_lights_switch

  Yard:
    control: hidden
    entities:
      - switch.patio_lights_switch
      - switch.patio_party_lights_switch
      - switch.fountains_switch
      ## outdoor speakers
      - switch.switch_one


#####################################################################
### Automation
#####################################################################
automation:
### Turn off the Party Lights - Weekdays
  - alias: Patio Party Lights Off Weekdays
    initial_state: 'on'
    trigger:
      platform: time
      at: '00:00:00'

    condition:
      - condition: time
        weekday:
          - sun
          - mon
          - tue
          - wed
          - thu

      - condition: state
        entity_id: switch.patio_party_lights_switch
        state: 'on'

    action:
  # outdoor Party lights
      - service: switch.turn_off
        entity_id: switch.patio_party_lights_switch


### Turn off the Party Lights - Weekends
  - alias: Patio Party Lights Off Weekends
    initial_state: 'on'
    trigger:
      platform: time
      at: '02:00:00'

    condition:
      - condition: time
        weekday:
          - sat
          - sun

      - condition: state
        entity_id: switch.patio_party_lights_switch
        state: 'on'

    action:
      - service: switch.turn_off
        entity_id: switch.patio_party_lights_switch
