#####################################################################
#    @package          :     patio
#    @description      :     patio, audio, and associated automations, scenes, etc.
#####################################################################
homeassistant:
  customize:

## groups
    group.living_room:
      order: 1


    switch.ge_Unknown_type4f50_id3031_switch_23_0:
      friendly_name: "Party Lights"
      icon: mdi:glass-mug

    switch.ge_12722_onoff_relay_switch_switch_7_0:
      friendly_name: "Patio Lights"
      icon: mdi:white-balance-incandescent

    switch.linear_fs20z_isolated_contact_fixture_module_switch_21_0:
      friendly_name: "Fountains"
      icon: mdi:beach

    switch.outdoor_speakers:
      friendly_name: "Outdoor Speakers"
      entity_picture: /local/music.ico


group:
  Exterior Lights:
    entities:
# patio lights
      - switch.ge_12722_onoff_relay_switch_switch_7_0
# party/christmas lights - GE outdoor wireless outlet
      - switch.ge_Unknown_type4f50_id3031_switch_23_0

  Yard:
    control: hidden
    entities:
# patio lights
      - switch.ge_12722_onoff_relay_switch_switch_7_0
# GE Outdoor wireless outlet; for Christmas lights, etc.
      - switch.ge_Unknown_type4f50_id3031_switch_23_0
# Pool fountains
      - switch.linear_fs20z_isolated_contact_fixture_module_switch_21_0
      - switch.outdoor_speakers

automation:
#####################################################################
### FOUNTAINS ON
#####################################################################
  - alias: turn on fountains
    trigger:
      - platform: sun
        event: sunrise
        offset: '01:30:00'

      - platform: state
        entity_id: group.all_devices
        from: 'not_home'
        to: 'home'

    condition:
      - condition: numeric_state
        entity_id: sensor.pws_wind_mph
        below: 10

      - condition: state
        entity_id: input_boolean.rain
        state: 'off'

      - condition: sun
        before: sunset

      - condition: state
        entity_id: group.all_devices
        state: 'home'

    action:
      - service: switch.turn_on
        data:
          entity_id: switch.linear_fs20z_isolated_contact_fixture_module_switch_21_0

#####################################################################
### FOUNTAINS OFF
#####################################################################
  - alias: turn off fountains
    hide_entity: True
    trigger:
      - platform: sun
        event: sunset
        offset: '00:05:00'

      - platform: state
        entity_id: input_boolean.rain
        from: 'off'
        to: 'on'
        for:
          minutes: 5

    condition:
      - condition: state
        entity_id: switch.linear_fs20z_isolated_contact_fixture_module_switch_21_0
        state: 'on'

    action:
      - service: switch.turn_off
        data:
          entity_id: switch.linear_fs20z_isolated_contact_fixture_module_switch_21_0

#####################################################################
### Turn off the Christmas Lights - Weekdays
#####################################################################
  - alias: turn off xmas lights weekdays
    trigger:
      platform: time
      at: '00:00:00'

    condition:
      - condition: time
        weekday:
          - sun
          - mon
          - tue
          - wed
          - thu

      - condition: state
        entity_id: switch.ge_unknown_type4f50_id3031_switch_23_0
        state: 'on'

    action:
  # outdoor Christmas lights
      - service: switch.turn_off
        entity_id: switch.ge_unknown_type4f50_id3031_switch_23_0

#####################################################################
### Turn off the Christmas Lights - Weekends
#####################################################################
  - alias: turn off xmas lights weekends
    trigger:
      platform: time
      at: '02:00:00'

    condition:
      - condition: time
        weekday:
          - sat
          - sun

      - condition: state
        entity_id: switch.ge_unknown_type4f50_id3031_switch_23_0
        state: 'on'

    action:
  # outdoor Christmas lights
      - service: switch.turn_off
        entity_id: switch.ge_unknown_type4f50_id3031_switch_23_0
