#####################################################################
#    @package          :     porch
#    @description      :     porch and associated automations, scenes, etc.
#####################################################################
homeassistant:
  customize:

## groups
    group.living_room:
      order: 1


## Porch Lights
    switch.ge_45609_onoff_relay_switch_switch_19_0:
      friendly_name: "South Porch Lights"
      icon: mdi:white-balance-incandescent

    switch.ge_45609_onoff_relay_switch_switch_20_0:
      friendly_name: "Front Porch Lights"
      icon: mdi:white-balance-incandescent


group:
  Porch:
    entities:
## south porch_lights
      - switch.ge_45609_onoff_relay_switch_switch_19_0
## front porch_lights
      - switch.ge_45609_onoff_relay_switch_switch_20_0


automation:
#####################################################################
### Turn on the porch lights at sunset
#####################################################################
- alias: porch lights on at sunset
  trigger:
    - platform: sun
      event: sunset
      offset: '00:10:00'

  action:
    - service: homeassistant.turn_on
      entity_id: group.porch

#####################################################################
### Turn off the porch lights
#####################################################################
- alias: porch lights off at sunrise
  trigger:
    - platform: sun
      event: sunrise
      offset: '-00:15:00'

  action:
    - service: homeassistant.turn_off
      entity_id: group.porch
