#####################################################################
#    @package          :     scenes
#    @description      :     scenes and scenarios for lighting, etc.
#####################################################################
homeassistant:
  customize_domain:
    scene:
      icon: mdi:play-circle

  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'scenes'

      contained: &contained
        <<: *customize
        haaska_hidden: true
        homebridge_hidden: true

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

      hidden: &hidden
        <<: *contained
        hidden: true

    ################################################
    ## Group
    ################################################
    group.lighting_scenes:
      <<: *contained

    group.interior_lights:
      haaska_name: "Interior Lights"

    group.stateless_lights:
      <<: *hidden

    ################################################
    ## Script
    ################################################
    script.morning_sequence:
      hidden: true
      icon: mdi:play-circle

    script.away:
      <<: *hidden
      friendly_name: "Away Mode"
      icon: mdi:play-circle

    script.company_mode:
      friendly_name: "Company Mode"
      icon: mdi:play-circle

    script.bedtime:
      friendly_name: "Bedtime"
      icon: mdi:hotel

    script.shutdown_lights:
      friendly_name: "Shutdown"
      icon: mdi:play-circle

    ################################################
    ## Scene
    ################################################
    scene.morning:
      icon: mdi:weather-sunset-up

    scene.living_room_bright:
      friendly_name: "Living Room Bright"
      icon: mdi:play-circle

    scene.living_room_normal:
      friendly_name: "Living Room Normal"
      icon: mdi:play-circle

    scene.living_room_cloudy:
      friendly_name: "Living Room Cloudy"
      icon: mdi:play-circle

    scene.living_room_dim:
      friendly_name: "Living Room Dim"
      icon: mdi:play-circle

    scene.movie_time:
      friendly_name: "Movie Time"
      icon: mdi:play-circle

    scene.movie_paused:
      icon: mdi:play-circle
      hidden: true
      haaska_hidden: true

    scene.movie_ended:
      icon: mdi:play-circle
      hidden: true
      haaska_hidden: true


#####################################################################
### Group
#####################################################################
group:
  Lighting Scenes:
    control: hidden
    entities:
      - script.bedtime
      - scene.morning
      - scene.movie_time
      - scene.living_room_dim
      - scene.living_room_cloudy
      - scene.living_room_normal
      - scene.living_room_bright
      - script.company_mode
      - script.shutdown_lights

  Interior Lights:
    entities:
      - group.accent_lights
      - light.entryway_lights
      - light.family_room_lights
      - light.master_bedroom
      - light.master_sitting_lamp
      - light.office_desk_lamp
      - light.master_bedroom_chandelier_level
      - switch.billiards_room_lights_switch
      - light.kitchen_lights_level
      - light.dining_room_chandelier_level

## Lights which do not report state (ceiling fans)
  Stateless Lights:
    entities:
      - switch.living_room_fan_light
      - switch.master_bedroom_fan_light


#####################################################################
### Scene
#####################################################################
scene:
  - name: Morning
    entities:

  # turn on the master bedroom chandelier
      light.master_bedroom_chandelier_level:
        state: on
        brightness: 50

  # turn on the accent_lights
      group.accent_lights: on

  # turn on the living room lamp
      light.living_room_lamp:
        state: on
        brightness: 254
        transition: 600

  # turn on the hue entry_lighting
      light.entryway_lights:
        state: on
        brightness: 140
        transition: 900

  # turn on the hue living_room_ceiling lights
      group.living_room_ceiling:
        state: on
        brightness: 140
        transition: 900

  # turn on the kitchen lights
      light.kitchen_lights_level:
        state: on
        brightness: 170


#####################################################################
### Script
#####################################################################
script:
  morning_sequence:
    sequence:

# turn on master bed chandelier
    - service: light.turn_on
      entity_id: light.master_bedroom_chandelier_level
      data:
        brightness: 50

### Turn on the accent lights
    - service: switch.turn_on
      entity_id: group.accent_lights

    - delay:
        minutes: 7

# turn on the living room lamp
    - service: light.turn_on
      entity_id: light.living_room_lamp
      data:
        brightness: 220
        transition: 60

    - delay:
        minutes: 7

# turn on the living room lights
    - service: light.turn_on
      entity_id:
        - light.entryway_lights
        - group.living_room_ceiling
      data:
        brightness: 140
        transition: 120

    - delay:
        minutes: 7

# turn on the kitchen lights
    - service: light.turn_on
      entity_id: light.kitchen_lights_level
      data:
        brightness: 170


### Bedtime
  bedtime:
    sequence:
    - service: lock.lock

    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.bedtime

### Turn off outlets and devices
    - service: homeassistant.turn_off
      entity_id: group.things

### Turn off the billiards room lights
    - service: switch.turn_off
      entity_id: switch.billiards_room

### Set master bedroom chandelier to dim
    - service: light.turn_on
      entity_id: light.master_bedroom_chandelier_level
      data:
        brightness: 50

### Turn on the under-bed lights
    - service: light.turn_on
      data:
        entity_id: light.under_bed_lights
        rgb_color: [0,55,55]

    - delay:
        minutes: 5

### dim master bed chandelier
    - service: light.turn_on
      entity_id: light.master_bedroom_chandelier_level
      data:
        brightness: 40

    - delay:
        minutes: 7

### turn_off master bed chandelier
    - service: light.turn_off
      entity_id: light.master_bedroom_chandelier_level
      data:
        transition: 60

# turn off all remaining lights
    - service: homeassistant.turn_off
      entity_id: group.interior_lights

    - delay:
        minutes: 1.5

### Turn off the under-bed lights
    - service: light.turn_off
      entity_id: light.under_bed_lights


### Away
  away:
    sequence:

# lock up
    - service: lock.lock

# turn off all lights (except porch)
    - service: homeassistant.turn_off
      entity_id: group.interior_lights

    - service: homeassistant.turn_off
      entity_id: group.exterior_lights

# turn off all the "things"
    - service: homeassistant.turn_off
      entity_id: group.things

    - service: notify.pushbullet
      data:
        title: "Away Mode ON"
        target: "device/Chrome"
        message: "It appears nobody's home; away mode activated."

    - service: notify.ios_iphwn666
      data:
        title: "Away Mode ON"
        message: "It appears nobody's home; away mode activated."


### Company Mode
  company_mode:
    sequence:
    - service: switch.turn_on
      entity_id: switch.outdoor_speakers

    - service: scene.turn_on
      entity_id: scene.living_room_bright

    - service: lock.unlock

## turn on the kitchen Lights
    - service: light.turn_on
      entity_id: light.kitchen_lights_level
      data:
        brightness: 175

## turn on the dining room light
    - service: light.turn_on
      entity_id: light.dining_room_chandelier_level
      data:
        brightness: 130

## turn on the Billiards Room lights
    - service: switch.turn_on
      entity_id: switch.billiards_room_lights_switch

## turn on the party lights
    - service: switch.turn_on
      entity_id: switch.patio_party_lights_switch

## turn on the pool light
    - service: switch.turn_on
      entity_id: switch.pool_light_switch


#####################################################################
### Automation
#####################################################################
automation:
### Weekday Wakeup
  - alias: weekday morning wakeup
    trigger:
      - platform: event
        event_type: good_morning

      - platform: time
        at: '05:55:00'

    condition:
      - condition: state
        entity_id: group.all_devices
        state: 'home'

      - condition: state
        entity_id: input_boolean.holiday
        state: 'off'

      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri

    action:
      - service: script.morning_sequence
