#####################################################################
#    @package          :     security_sensors
#    @description      :     security_sensors and associated automations, etc.
#####################################################################
homeassistant:
  customize:
## Fibaro Motion
    sensor.fibaro_state:
      friendly_name: "Fibaro Motion Status"
      icon: mdi:run

    sensor.fibaro_system_fgms001_motion_sensor_luminance_22_3:
      friendly_name: "Fibaro Light Sensor"
      icon: mdi:white-balance-sunny

## Camera Sensors
    sensor.kitchen_ptz_motion_detected:
      friendly_name: "Kitchen PTZ Motion"
      icon: mdi:run

    sensor.north_ptz_motion_detected:
      friendly_name: "North PTZ Motion"
      icon: mdi:run

    sensor.kitchen_ptz_ptz_preset:
      friendly_name: "Kitchen PTZ Preset"
      icon: mdi:arrow-expand-all

    sensor.north_ptz_ptz_preset:
      friendly_name: "North PTZ Preset"
      icon: mdi:arrow-expand-all

    sensor.kitchen_ptz_sd_used:
      friendly_name: "Kitchen PTZ SD Card"
      icon: mdi:sd

    sensor.north_ptz_sd_used:
      friendly_name: "North PTZ SD Card"
      icon: mdi:sd

    sensor.crime:
      icon: mdi:bomb


group:
  Sensors:
    entities:
      - sensor.fibaro_state
      - sensor.kitchen_ptz_motion_detected
      - sensor.north_ptz_motion_detected
      - sensor.fibaro_system_fgms001_motion_sensor_luminance_22_3
      - sensor.crime


sensor:
#####################################################################
### Fibaro Motion Detector status
#####################################################################
  - platform: template
    sensors:
      fibaro_state:
        value_template: >-
          {% set state = states('sensor.fibaro_system_fgms001_motion_sensor_burglar_22_10') %}
          {% if state == '0' %}
            Idle
          {% elif state == '8' %}
            Motion Detected
          {% elif state == '3' %}
            Tamper
          {% elif state == '254' %}
            Sleeping
          {% else %}
            {{ state|title }}
          {% endif %}

#####################################################################
### Amcrest Camera Sensors
#####################################################################
  - platform: amcrest
    host: !secret north_ptz_host
    port: !secret north_ptz_port
    name: "North PTZ"
    username: !secret camera_user
    password: !secret camera_password
    monitored_conditions:
      - motion_detector
  #    - sdcard
  #    - ptz_preset

  - platform: amcrest
    host: !secret kitchen_ptz_host
    port: !secret kitchen_ptz_port
    name: "Kitchen PTZ"
    username: !secret camera_user
    password: !secret camera_password
    monitored_conditions:
      - motion_detector
  #    - sdcard
  #    - ptz_preset

#####################################################################
### Crime Reports
#####################################################################
  - platform: crimereports
    name: Crime
    radius: 4000
    exclude:
    - Disorder
    - Drugs
    - Other
    - Pedestrian Stop
    - Proactive Policing
    - Quality of Life
    - Traffic
    - Vehicle Recovery
    - Vehicle Stop


