############################################################################
#    @package          :     other components
#    @description      :     spares, testing, and associated automations, scenes, etc.
############################################################################
homeassistant:
  customize:
    input_boolean.condition_1:
      friendly_name: "Test Condition 1"
      icon: mdi:checkbox-marked-circle

    input_boolean.condition_2:
      friendly_name: "Test Condition 2"
      icon: mdi:checkbox-marked-circle

    input_boolean.condition_3:
      friendly_name: "Test Condition 3"
      icon: mdi:checkbox-marked-circle

    input_boolean.condition_4:
      friendly_name: "Test Condition 4"
      icon: mdi:checkbox-marked-circle

    input_boolean.condition_5:
      friendly_name: "Test Condition 5"
      icon: mdi:checkbox-marked-circle

## Accent - Spare
    switch.rf_switch_3:
      hidden: true
      haaska_hidden: true
      friendly_name: "Staircase Christmas Lights"
      icon: mdi:stocking


group:
  Things:
    entities:
      - switch.humidifier
# Fountains
      - switch.linear_fs20z_isolated_contact_fixture_module_switch_21_0
      - switch.outdoor_speakers

  Triggers:
    control: hidden
    entities:
      - script.desk_lamp
      - script.light_test
      - input_boolean.state_change
      - automation.raining
      - script.time_temp
      - script.morning_weekday

  Test Conditions:
    control: hidden
    entities:
      - input_boolean.condition_1
      - input_boolean.condition_2
      - input_boolean.condition_3
      - input_boolean.condition_4
      - input_boolean.condition_5

  HVAC Downstairs:
    entities:
      - climate.2gig_technologies_ct101_thermostat_iris_cooling_1_18_2
      - climate.2gig_technologies_ct101_thermostat_iris_heating_1_18_1

  HVAC Upstairs:
    entities:
      - climate.2gig_technologies_ct101_thermostat_iris_cooling_1_42_2
      - climate.2gig_technologies_ct101_thermostat_iris_heating_1_42_1



