############################################################################
#    @package          :     views
#    @description      :     views visible on UI
############################################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'views'

      contained: &contained
        <<: *customize
        haaska_hidden: true
        homebridge_hidden: true

      exposed: &exposed
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

      hidden: &hidden
        <<: *contained
        hidden: true

    ################################################
    ## Group
    ################################################
    group.default_view:
      <<: *contained

    group.security:
      <<: *contained

    group.downstairs:
      <<: *contained

    group.upstairs:
      <<: *contained

    group.climate:
      <<: *contained

    group.weather:
      <<: *contained

    group.interior:
      <<: *contained

    group.exterior:
      <<: *contained

    group.scenes:
      <<: *contained

    group.media:
      <<: *contained

    group.system:
      <<: *contained

    group.lab:
      <<: *contained

  ################################################
  ## Customize Global
  ################################################
  customize_glob:
    "group.all_*":
      <<: *contained


#####################################################################
### Group
#####################################################################
group:
  default_view:
    name: Home
    view: yes
    icon: mdi:castle
    entities:
      - group.travel_megs
      - group.travel_rick
      - group.device_status
      - group.alerts


  security:
    name: Security
    view: yes
    icon: mdi:security-home
    entities:
      - group.security_override
      - group.door_locks
      - group.sensors
      - group.cameras
      - group.breaches


  downstairs:
    name: Downstairs
    view: yes
    icon: mdi:arrow-down-bold-circle-outline
    entities:
      - group.living_room
      - group.entry_lighting
      - group.living_room_fan
      - group.kitchen
      - group.dining_room
      - group.accent_lights
      - group.office
      - group.billiards_room


  upstairs:
    name: Upstairs
    view: yes
    icon: mdi:arrow-up-bold-circle-outline
    entities:
      - group.master_bedroom
      - group.master_bedroom_fan
      - group.master_bed_lights
      - group.master_bath
      - media_player.kodi_bedroom


  climate:
    name: Climate
    view: yes
    icon: mdi:air-conditioner
    entities:
      - group.upstairs_climate
      - group.upstairs_cooling
      - group.upstairs_heating
      - group.downstairs_climate
      - group.downstairs_ecobee


  weather:
    name: Weather
    view: yes
    icon: mdi:weather-sunny
    entities:
      - sun.sun
      - sensor.moon
      - group.weather_summary
      - group.weather_details
      - group.precipitation


  exterior:
    name: Exterior
    view: yes
    icon: mdi:tree
    entities:
      - group.porch
      - group.yard
      - group.pool


  scenes:
    name: Scenes
    icon: mdi:creation
    view: yes
    entities:
      - group.lighting_scenes
      #- group.light_and_switch_override


  media:
    name: Media
    view: yes
    icon: mdi:theater
    entities:
      - group.living_room_tv
      - group.directv
      - group.onkyo_amp
      - group.media_players


  system:
    name: System
    icon: mdi:server
    view: yes
    entities:
      - updater.updater
      - group.ha_status
      - group.speedtest
      - group.downloads


  lab:
    name: Lab
    view: yes
    icon: mdi:test-tube
    entities:
      - group.triggers
      - group.test_conditions
