#####################################################################
#    @package          :     weather
#    @description      :     weather sensors and associated automations, etc.
#####################################################################
homeassistant:
  customize:

    input_boolean.rain:
      haaska_hidden: true

    sensor.dark_sky_humidity:
      friendly_name: "Humidity"
      icon: mdi:water-percent
    sensor.dark_sky_dew_point:
      friendly_name: "Dew Point"
      icon: mdi:water
    sensor.dark_sky_daily_summary:
      friendly_name: "Daily Summary"
      icon: mdi:calendar-clock
    sensor.dark_sky_pressure:
      friendly_name: "Pressure"
      icon: mdi:nature
    sensor.dark_sky_temperature:
      icon: mdi:thermometer
      friendly_name: "Temperature"
    sensor.dark_sky_wind_speed:
      icon: mdi:weather-windy
      friendly_name: "Wind Speed"
    sensor.dark_sky_summary:
      friendly_name: "Current Conditions"
      icon: mdi:map-marker-radius
    sensor.dark_sky_precip_probability:
      friendly_name: "Chance Rain"
      icon: mdi:weather-rainy
    sensor.dark_sky_precip_intensity:
      friendly_name: "Predicted Rain"
      icon: mdi:weather-rainy
    sensor.dark_sky_visibility:
      friendly_name: "Visibility"
    sensor.dark_sky_cloud_coverage:
      friendly_name: "Cloud Cover"
      icon: mdi:weather-partlycloudy
    sensor.dark_sky_wind_bearing:
      friendly_name: "Wind Bearing"
      icon: mdi:compass
    sensor.dark_sky_apparent_temperature:
      friendly_name: "Feels Like"
    sensor.dark_sky_nearest_storm_distance:
      friendly_name: "Nearest Storm"
      icon: mdi:weather-lightning-rainy

  ## WUnderground PWS 
    sensor.pws_weather:
      friendly_name: "Current Condition"
    sensor.pws_temp_f:
      friendly_name: "Temperature"
    sensor.pws_feelslike_string:
      friendly_name: "Feels Like"
      icon: mdi:thermometer
    sensor.pws_precip_today_string:
      friendly_name: "Precipitation"
      icon: mdi:weather-rainy
    sensor.pws_wind_string:
      friendly_name: "Wind"
      icon: mdi:weather-windy
    sensor.pws_heat_index_string:
      friendly_name: "Heat Index"
      icon: mdi:weather-sunny
    sensor.pws_relative_humidity:
      friendly_name: "Humidity"
      icon: mdi:water-percent
    sensor.pws_dewpoint_string:
      friendly_name: "Dew Point"
      icon: mdi:water
    sensor.pws_pressure_in:
      friendly_name: "Pressure Inches"
      icon: mdi:thermometer-lines
    sensor.pws_pressure_mb:
      friendly_name: "Pressure Mbar"
      icon: mdi:nature
    sensor.pws_solarradiation:
      friendly_name: "Radiation"
      icon: mdi:radioactive
    sensor.pws_uv:
      friendly_name: "UV Index"
      icon: mdi:sunglasses
    sensor.pws_visibility_mi:
      friendly_name: "Visibility"


# group config
group:
  Weather Summary:
    entities:
      - sensor.season
      - input_slider.season_summer
      - input_slider.season_winter
      - sensor.pws_weather
      - sensor.dark_sky_daily_summary
      - sensor.pws_temp_f
      - sensor.pws_feelslike_string
      - sensor.pws_wind_string
      - sensor.pws_relative_humidity
      - sensor.pws_dewpoint_string

  Precipitation:
    entities:
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_precip_intensity
      - sensor.pws_precip_today_string
      - sensor.dark_sky_nearest_storm_distance
      - input_boolean.rain

  Weather Details:
    entities:
      - sensor.dark_sky_cloud_coverage
      - sensor.pws_heat_index_string
      - sensor.pws_pressure_in
      - sensor.pws_pressure_mb
      - sensor.pws_solarradiation
      - sensor.pws_uv
      - sensor.pws_visibility_mi


sensor:
#####################################################################
### Seasons
#####################################################################
  - platform: template
    sensors:
      season:
        friendly_name: "Seasonal Condition"
        value_template: >-
          {% set temperature = states('sensor.pws_temp_f')|float(none) %}
          {% set winter_temp = states.input_slider.season_winter.state|default(62)|float %}
          {% set summer_temp = states.input_slider.season_summer.state|default(74)|float %}
          {% if temperature is none %}
            {{ states('sensor.pws_temp_f') }}
          {% elif temperature < winter_temp %}
            Winter
          {% elif temperature > summer_temp %}
            Summer
          {% else %}
            Awesome
          {% endif %}

#####################################################################
### WEATHER
#####################################################################
  - platform: moon

  - platform: wunderground
    api_key: !secret wu_api_key
    monitored_conditions:
      - weather
      - alerts
      - temp_f
      - station_id
      - feelslike_f
      - feelslike_string
      - heat_index_f
      - heat_index_string
      - dewpoint_f
      - dewpoint_string
      - wind_mph
      - UV
      - pressure_in
      - pressure_mb
      - wind_dir
      - wind_string
      - relative_humidity
      - visibility_mi
      - precip_today_in
      - precip_today_string
      - solarradiation
      - observation_time

  - platform: darksky
    api_key: !secret forecast_api_key
    monitored_conditions:
      - nearest_storm_distance
      - cloud_cover
      - daily_summary
      - precip_intensity
      - precip_probability
      - precip_intensity_max


#automation:
